// Code generated by internal/gen; DO NOT EDIT.

package evdev

// EvType is an evdev event type (the EV_* constants).
type EvType uint16

// EvCode is an evdev event code within a type's namespace (KEY_*, REL_*, ...).
type EvCode uint16

// BusType identifies the bus a device is attached to (the BUS_* constants).
type BusType uint16

// InputProp is a device property (the INPUT_PROP_* constants).
type InputProp uint16

const (
	EV_SYN       EvType = 0x0
	EV_KEY       EvType = 0x1
	EV_REL       EvType = 0x2
	EV_ABS       EvType = 0x3
	EV_MSC       EvType = 0x4
	EV_SW        EvType = 0x5
	EV_LED       EvType = 0x11
	EV_SND       EvType = 0x12
	EV_REP       EvType = 0x14
	EV_FF        EvType = 0x15
	EV_PWR       EvType = 0x16
	EV_FF_STATUS EvType = 0x17
	EV_MAX       EvType = 0x1f
	EV_CNT       EvType = 0x20
)

const (
	ABS_X                        EvCode = 0x0
	ABS_Y                        EvCode = 0x1
	ABS_Z                        EvCode = 0x2
	ABS_RX                       EvCode = 0x3
	ABS_RY                       EvCode = 0x4
	ABS_RZ                       EvCode = 0x5
	ABS_THROTTLE                 EvCode = 0x6
	ABS_RUDDER                   EvCode = 0x7
	ABS_WHEEL                    EvCode = 0x8
	ABS_GAS                      EvCode = 0x9
	ABS_BRAKE                    EvCode = 0xa
	ABS_HAT0X                    EvCode = 0x10
	ABS_HAT0Y                    EvCode = 0x11
	ABS_HAT1X                    EvCode = 0x12
	ABS_HAT1Y                    EvCode = 0x13
	ABS_HAT2X                    EvCode = 0x14
	ABS_HAT2Y                    EvCode = 0x15
	ABS_HAT3X                    EvCode = 0x16
	ABS_HAT3Y                    EvCode = 0x17
	ABS_PRESSURE                 EvCode = 0x18
	ABS_DISTANCE                 EvCode = 0x19
	ABS_TILT_X                   EvCode = 0x1a
	ABS_TILT_Y                   EvCode = 0x1b
	ABS_TOOL_WIDTH               EvCode = 0x1c
	ABS_VOLUME                   EvCode = 0x20
	ABS_PROFILE                  EvCode = 0x21
	ABS_SND_PROFILE              EvCode = 0x22
	ABS_MISC                     EvCode = 0x28
	ABS_RESERVED                 EvCode = 0x2e
	ABS_MT_SLOT                  EvCode = 0x2f
	ABS_MT_TOUCH_MAJOR           EvCode = 0x30
	ABS_MT_TOUCH_MINOR           EvCode = 0x31
	ABS_MT_WIDTH_MAJOR           EvCode = 0x32
	ABS_MT_WIDTH_MINOR           EvCode = 0x33
	ABS_MT_ORIENTATION           EvCode = 0x34
	ABS_MT_POSITION_X            EvCode = 0x35
	ABS_MT_POSITION_Y            EvCode = 0x36
	ABS_MT_TOOL_TYPE             EvCode = 0x37
	ABS_MT_BLOB_ID               EvCode = 0x38
	ABS_MT_TRACKING_ID           EvCode = 0x39
	ABS_MT_PRESSURE              EvCode = 0x3a
	ABS_MT_DISTANCE              EvCode = 0x3b
	ABS_MT_TOOL_X                EvCode = 0x3c
	ABS_MT_TOOL_Y                EvCode = 0x3d
	ABS_MAX                      EvCode = 0x3f
	ABS_CNT                      EvCode = 0x40
	KEY_RESERVED                 EvCode = 0x0
	KEY_ESC                      EvCode = 0x1
	KEY_1                        EvCode = 0x2
	KEY_2                        EvCode = 0x3
	KEY_3                        EvCode = 0x4
	KEY_4                        EvCode = 0x5
	KEY_5                        EvCode = 0x6
	KEY_6                        EvCode = 0x7
	KEY_7                        EvCode = 0x8
	KEY_8                        EvCode = 0x9
	KEY_9                        EvCode = 0xa
	KEY_0                        EvCode = 0xb
	KEY_MINUS                    EvCode = 0xc
	KEY_EQUAL                    EvCode = 0xd
	KEY_BACKSPACE                EvCode = 0xe
	KEY_TAB                      EvCode = 0xf
	KEY_Q                        EvCode = 0x10
	KEY_W                        EvCode = 0x11
	KEY_E                        EvCode = 0x12
	KEY_R                        EvCode = 0x13
	KEY_T                        EvCode = 0x14
	KEY_Y                        EvCode = 0x15
	KEY_U                        EvCode = 0x16
	KEY_I                        EvCode = 0x17
	KEY_O                        EvCode = 0x18
	KEY_P                        EvCode = 0x19
	KEY_LEFTBRACE                EvCode = 0x1a
	KEY_RIGHTBRACE               EvCode = 0x1b
	KEY_ENTER                    EvCode = 0x1c
	KEY_LEFTCTRL                 EvCode = 0x1d
	KEY_A                        EvCode = 0x1e
	KEY_S                        EvCode = 0x1f
	KEY_D                        EvCode = 0x20
	KEY_F                        EvCode = 0x21
	KEY_G                        EvCode = 0x22
	KEY_H                        EvCode = 0x23
	KEY_J                        EvCode = 0x24
	KEY_K                        EvCode = 0x25
	KEY_L                        EvCode = 0x26
	KEY_SEMICOLON                EvCode = 0x27
	KEY_APOSTROPHE               EvCode = 0x28
	KEY_GRAVE                    EvCode = 0x29
	KEY_LEFTSHIFT                EvCode = 0x2a
	KEY_BACKSLASH                EvCode = 0x2b
	KEY_Z                        EvCode = 0x2c
	KEY_X                        EvCode = 0x2d
	KEY_C                        EvCode = 0x2e
	KEY_V                        EvCode = 0x2f
	KEY_B                        EvCode = 0x30
	KEY_N                        EvCode = 0x31
	KEY_M                        EvCode = 0x32
	KEY_COMMA                    EvCode = 0x33
	KEY_DOT                      EvCode = 0x34
	KEY_SLASH                    EvCode = 0x35
	KEY_RIGHTSHIFT               EvCode = 0x36
	KEY_KPASTERISK               EvCode = 0x37
	KEY_LEFTALT                  EvCode = 0x38
	KEY_SPACE                    EvCode = 0x39
	KEY_CAPSLOCK                 EvCode = 0x3a
	KEY_F1                       EvCode = 0x3b
	KEY_F2                       EvCode = 0x3c
	KEY_F3                       EvCode = 0x3d
	KEY_F4                       EvCode = 0x3e
	KEY_F5                       EvCode = 0x3f
	KEY_F6                       EvCode = 0x40
	KEY_F7                       EvCode = 0x41
	KEY_F8                       EvCode = 0x42
	KEY_F9                       EvCode = 0x43
	KEY_F10                      EvCode = 0x44
	KEY_NUMLOCK                  EvCode = 0x45
	KEY_SCROLLLOCK               EvCode = 0x46
	KEY_KP7                      EvCode = 0x47
	KEY_KP8                      EvCode = 0x48
	KEY_KP9                      EvCode = 0x49
	KEY_KPMINUS                  EvCode = 0x4a
	KEY_KP4                      EvCode = 0x4b
	KEY_KP5                      EvCode = 0x4c
	KEY_KP6                      EvCode = 0x4d
	KEY_KPPLUS                   EvCode = 0x4e
	KEY_KP1                      EvCode = 0x4f
	KEY_KP2                      EvCode = 0x50
	KEY_KP3                      EvCode = 0x51
	KEY_KP0                      EvCode = 0x52
	KEY_KPDOT                    EvCode = 0x53
	KEY_ZENKAKUHANKAKU           EvCode = 0x55
	KEY_102ND                    EvCode = 0x56
	KEY_F11                      EvCode = 0x57
	KEY_F12                      EvCode = 0x58
	KEY_RO                       EvCode = 0x59
	KEY_KATAKANA                 EvCode = 0x5a
	KEY_HIRAGANA                 EvCode = 0x5b
	KEY_HENKAN                   EvCode = 0x5c
	KEY_KATAKANAHIRAGANA         EvCode = 0x5d
	KEY_MUHENKAN                 EvCode = 0x5e
	KEY_KPJPCOMMA                EvCode = 0x5f
	KEY_KPENTER                  EvCode = 0x60
	KEY_RIGHTCTRL                EvCode = 0x61
	KEY_KPSLASH                  EvCode = 0x62
	KEY_SYSRQ                    EvCode = 0x63
	KEY_RIGHTALT                 EvCode = 0x64
	KEY_LINEFEED                 EvCode = 0x65
	KEY_HOME                     EvCode = 0x66
	KEY_UP                       EvCode = 0x67
	KEY_PAGEUP                   EvCode = 0x68
	KEY_LEFT                     EvCode = 0x69
	KEY_RIGHT                    EvCode = 0x6a
	KEY_END                      EvCode = 0x6b
	KEY_DOWN                     EvCode = 0x6c
	KEY_PAGEDOWN                 EvCode = 0x6d
	KEY_INSERT                   EvCode = 0x6e
	KEY_DELETE                   EvCode = 0x6f
	KEY_MACRO                    EvCode = 0x70
	KEY_MUTE                     EvCode = 0x71
	KEY_VOLUMEDOWN               EvCode = 0x72
	KEY_VOLUMEUP                 EvCode = 0x73
	KEY_POWER                    EvCode = 0x74
	KEY_KPEQUAL                  EvCode = 0x75
	KEY_KPPLUSMINUS              EvCode = 0x76
	KEY_PAUSE                    EvCode = 0x77
	KEY_SCALE                    EvCode = 0x78
	KEY_KPCOMMA                  EvCode = 0x79
	KEY_HANGEUL                  EvCode = 0x7a
	KEY_HANGUEL                  EvCode = 0x7a
	KEY_HANJA                    EvCode = 0x7b
	KEY_YEN                      EvCode = 0x7c
	KEY_LEFTMETA                 EvCode = 0x7d
	KEY_RIGHTMETA                EvCode = 0x7e
	KEY_COMPOSE                  EvCode = 0x7f
	KEY_STOP                     EvCode = 0x80
	KEY_AGAIN                    EvCode = 0x81
	KEY_PROPS                    EvCode = 0x82
	KEY_UNDO                     EvCode = 0x83
	KEY_FRONT                    EvCode = 0x84
	KEY_COPY                     EvCode = 0x85
	KEY_OPEN                     EvCode = 0x86
	KEY_PASTE                    EvCode = 0x87
	KEY_FIND                     EvCode = 0x88
	KEY_CUT                      EvCode = 0x89
	KEY_HELP                     EvCode = 0x8a
	KEY_MENU                     EvCode = 0x8b
	KEY_CALC                     EvCode = 0x8c
	KEY_SETUP                    EvCode = 0x8d
	KEY_SLEEP                    EvCode = 0x8e
	KEY_WAKEUP                   EvCode = 0x8f
	KEY_FILE                     EvCode = 0x90
	KEY_SENDFILE                 EvCode = 0x91
	KEY_DELETEFILE               EvCode = 0x92
	KEY_XFER                     EvCode = 0x93
	KEY_PROG1                    EvCode = 0x94
	KEY_PROG2                    EvCode = 0x95
	KEY_WWW                      EvCode = 0x96
	KEY_MSDOS                    EvCode = 0x97
	KEY_COFFEE                   EvCode = 0x98
	KEY_SCREENLOCK               EvCode = 0x98
	KEY_ROTATE_DISPLAY           EvCode = 0x99
	KEY_DIRECTION                EvCode = 0x99
	KEY_CYCLEWINDOWS             EvCode = 0x9a
	KEY_MAIL                     EvCode = 0x9b
	KEY_BOOKMARKS                EvCode = 0x9c
	KEY_COMPUTER                 EvCode = 0x9d
	KEY_BACK                     EvCode = 0x9e
	KEY_FORWARD                  EvCode = 0x9f
	KEY_CLOSECD                  EvCode = 0xa0
	KEY_EJECTCD                  EvCode = 0xa1
	KEY_EJECTCLOSECD             EvCode = 0xa2
	KEY_NEXTSONG                 EvCode = 0xa3
	KEY_PLAYPAUSE                EvCode = 0xa4
	KEY_PREVIOUSSONG             EvCode = 0xa5
	KEY_STOPCD                   EvCode = 0xa6
	KEY_RECORD                   EvCode = 0xa7
	KEY_REWIND                   EvCode = 0xa8
	KEY_PHONE                    EvCode = 0xa9
	KEY_ISO                      EvCode = 0xaa
	KEY_CONFIG                   EvCode = 0xab
	KEY_HOMEPAGE                 EvCode = 0xac
	KEY_REFRESH                  EvCode = 0xad
	KEY_EXIT                     EvCode = 0xae
	KEY_MOVE                     EvCode = 0xaf
	KEY_EDIT                     EvCode = 0xb0
	KEY_SCROLLUP                 EvCode = 0xb1
	KEY_SCROLLDOWN               EvCode = 0xb2
	KEY_KPLEFTPAREN              EvCode = 0xb3
	KEY_KPRIGHTPAREN             EvCode = 0xb4
	KEY_NEW                      EvCode = 0xb5
	KEY_REDO                     EvCode = 0xb6
	KEY_F13                      EvCode = 0xb7
	KEY_F14                      EvCode = 0xb8
	KEY_F15                      EvCode = 0xb9
	KEY_F16                      EvCode = 0xba
	KEY_F17                      EvCode = 0xbb
	KEY_F18                      EvCode = 0xbc
	KEY_F19                      EvCode = 0xbd
	KEY_F20                      EvCode = 0xbe
	KEY_F21                      EvCode = 0xbf
	KEY_F22                      EvCode = 0xc0
	KEY_F23                      EvCode = 0xc1
	KEY_F24                      EvCode = 0xc2
	KEY_PLAYCD                   EvCode = 0xc8
	KEY_PAUSECD                  EvCode = 0xc9
	KEY_PROG3                    EvCode = 0xca
	KEY_PROG4                    EvCode = 0xcb
	KEY_ALL_APPLICATIONS         EvCode = 0xcc
	KEY_DASHBOARD                EvCode = 0xcc
	KEY_SUSPEND                  EvCode = 0xcd
	KEY_CLOSE                    EvCode = 0xce
	KEY_PLAY                     EvCode = 0xcf
	KEY_FASTFORWARD              EvCode = 0xd0
	KEY_BASSBOOST                EvCode = 0xd1
	KEY_PRINT                    EvCode = 0xd2
	KEY_HP                       EvCode = 0xd3
	KEY_CAMERA                   EvCode = 0xd4
	KEY_SOUND                    EvCode = 0xd5
	KEY_QUESTION                 EvCode = 0xd6
	KEY_EMAIL                    EvCode = 0xd7
	KEY_CHAT                     EvCode = 0xd8
	KEY_SEARCH                   EvCode = 0xd9
	KEY_CONNECT                  EvCode = 0xda
	KEY_FINANCE                  EvCode = 0xdb
	KEY_SPORT                    EvCode = 0xdc
	KEY_SHOP                     EvCode = 0xdd
	KEY_ALTERASE                 EvCode = 0xde
	KEY_CANCEL                   EvCode = 0xdf
	KEY_BRIGHTNESSDOWN           EvCode = 0xe0
	KEY_BRIGHTNESSUP             EvCode = 0xe1
	KEY_MEDIA                    EvCode = 0xe2
	KEY_SWITCHVIDEOMODE          EvCode = 0xe3
	KEY_KBDILLUMTOGGLE           EvCode = 0xe4
	KEY_KBDILLUMDOWN             EvCode = 0xe5
	KEY_KBDILLUMUP               EvCode = 0xe6
	KEY_SEND                     EvCode = 0xe7
	KEY_REPLY                    EvCode = 0xe8
	KEY_FORWARDMAIL              EvCode = 0xe9
	KEY_SAVE                     EvCode = 0xea
	KEY_DOCUMENTS                EvCode = 0xeb
	KEY_BATTERY                  EvCode = 0xec
	KEY_BLUETOOTH                EvCode = 0xed
	KEY_WLAN                     EvCode = 0xee
	KEY_UWB                      EvCode = 0xef
	KEY_UNKNOWN                  EvCode = 0xf0
	KEY_VIDEO_NEXT               EvCode = 0xf1
	KEY_VIDEO_PREV               EvCode = 0xf2
	KEY_BRIGHTNESS_CYCLE         EvCode = 0xf3
	KEY_BRIGHTNESS_AUTO          EvCode = 0xf4
	KEY_BRIGHTNESS_ZERO          EvCode = 0xf4
	KEY_DISPLAY_OFF              EvCode = 0xf5
	KEY_WWAN                     EvCode = 0xf6
	KEY_WIMAX                    EvCode = 0xf6
	KEY_RFKILL                   EvCode = 0xf7
	KEY_MICMUTE                  EvCode = 0xf8
	BTN_MISC                     EvCode = 0x100
	BTN_0                        EvCode = 0x100
	BTN_1                        EvCode = 0x101
	BTN_2                        EvCode = 0x102
	BTN_3                        EvCode = 0x103
	BTN_4                        EvCode = 0x104
	BTN_5                        EvCode = 0x105
	BTN_6                        EvCode = 0x106
	BTN_7                        EvCode = 0x107
	BTN_8                        EvCode = 0x108
	BTN_9                        EvCode = 0x109
	BTN_MOUSE                    EvCode = 0x110
	BTN_LEFT                     EvCode = 0x110
	BTN_RIGHT                    EvCode = 0x111
	BTN_MIDDLE                   EvCode = 0x112
	BTN_SIDE                     EvCode = 0x113
	BTN_EXTRA                    EvCode = 0x114
	BTN_FORWARD                  EvCode = 0x115
	BTN_BACK                     EvCode = 0x116
	BTN_TASK                     EvCode = 0x117
	BTN_JOYSTICK                 EvCode = 0x120
	BTN_TRIGGER                  EvCode = 0x120
	BTN_THUMB                    EvCode = 0x121
	BTN_THUMB2                   EvCode = 0x122
	BTN_TOP                      EvCode = 0x123
	BTN_TOP2                     EvCode = 0x124
	BTN_PINKIE                   EvCode = 0x125
	BTN_BASE                     EvCode = 0x126
	BTN_BASE2                    EvCode = 0x127
	BTN_BASE3                    EvCode = 0x128
	BTN_BASE4                    EvCode = 0x129
	BTN_BASE5                    EvCode = 0x12a
	BTN_BASE6                    EvCode = 0x12b
	BTN_DEAD                     EvCode = 0x12f
	BTN_GAMEPAD                  EvCode = 0x130
	BTN_SOUTH                    EvCode = 0x130
	BTN_A                        EvCode = 0x130
	BTN_EAST                     EvCode = 0x131
	BTN_B                        EvCode = 0x131
	BTN_C                        EvCode = 0x132
	BTN_NORTH                    EvCode = 0x133
	BTN_X                        EvCode = 0x133
	BTN_WEST                     EvCode = 0x134
	BTN_Y                        EvCode = 0x134
	BTN_Z                        EvCode = 0x135
	BTN_TL                       EvCode = 0x136
	BTN_TR                       EvCode = 0x137
	BTN_TL2                      EvCode = 0x138
	BTN_TR2                      EvCode = 0x139
	BTN_SELECT                   EvCode = 0x13a
	BTN_START                    EvCode = 0x13b
	BTN_MODE                     EvCode = 0x13c
	BTN_THUMBL                   EvCode = 0x13d
	BTN_THUMBR                   EvCode = 0x13e
	BTN_DIGI                     EvCode = 0x140
	BTN_TOOL_PEN                 EvCode = 0x140
	BTN_TOOL_RUBBER              EvCode = 0x141
	BTN_TOOL_BRUSH               EvCode = 0x142
	BTN_TOOL_PENCIL              EvCode = 0x143
	BTN_TOOL_AIRBRUSH            EvCode = 0x144
	BTN_TOOL_FINGER              EvCode = 0x145
	BTN_TOOL_MOUSE               EvCode = 0x146
	BTN_TOOL_LENS                EvCode = 0x147
	BTN_TOOL_QUINTTAP            EvCode = 0x148
	BTN_STYLUS3                  EvCode = 0x149
	BTN_TOUCH                    EvCode = 0x14a
	BTN_STYLUS                   EvCode = 0x14b
	BTN_STYLUS2                  EvCode = 0x14c
	BTN_TOOL_DOUBLETAP           EvCode = 0x14d
	BTN_TOOL_TRIPLETAP           EvCode = 0x14e
	BTN_TOOL_QUADTAP             EvCode = 0x14f
	BTN_WHEEL                    EvCode = 0x150
	BTN_GEAR_DOWN                EvCode = 0x150
	BTN_GEAR_UP                  EvCode = 0x151
	KEY_OK                       EvCode = 0x160
	KEY_SELECT                   EvCode = 0x161
	KEY_GOTO                     EvCode = 0x162
	KEY_CLEAR                    EvCode = 0x163
	KEY_POWER2                   EvCode = 0x164
	KEY_OPTION                   EvCode = 0x165
	KEY_INFO                     EvCode = 0x166
	KEY_TIME                     EvCode = 0x167
	KEY_VENDOR                   EvCode = 0x168
	KEY_ARCHIVE                  EvCode = 0x169
	KEY_PROGRAM                  EvCode = 0x16a
	KEY_CHANNEL                  EvCode = 0x16b
	KEY_FAVORITES                EvCode = 0x16c
	KEY_EPG                      EvCode = 0x16d
	KEY_PVR                      EvCode = 0x16e
	KEY_MHP                      EvCode = 0x16f
	KEY_LANGUAGE                 EvCode = 0x170
	KEY_TITLE                    EvCode = 0x171
	KEY_SUBTITLE                 EvCode = 0x172
	KEY_ANGLE                    EvCode = 0x173
	KEY_FULL_SCREEN              EvCode = 0x174
	KEY_ZOOM                     EvCode = 0x174
	KEY_MODE                     EvCode = 0x175
	KEY_KEYBOARD                 EvCode = 0x176
	KEY_ASPECT_RATIO             EvCode = 0x177
	KEY_SCREEN                   EvCode = 0x177
	KEY_PC                       EvCode = 0x178
	KEY_TV                       EvCode = 0x179
	KEY_TV2                      EvCode = 0x17a
	KEY_VCR                      EvCode = 0x17b
	KEY_VCR2                     EvCode = 0x17c
	KEY_SAT                      EvCode = 0x17d
	KEY_SAT2                     EvCode = 0x17e
	KEY_CD                       EvCode = 0x17f
	KEY_TAPE                     EvCode = 0x180
	KEY_RADIO                    EvCode = 0x181
	KEY_TUNER                    EvCode = 0x182
	KEY_PLAYER                   EvCode = 0x183
	KEY_TEXT                     EvCode = 0x184
	KEY_DVD                      EvCode = 0x185
	KEY_AUX                      EvCode = 0x186
	KEY_MP3                      EvCode = 0x187
	KEY_AUDIO                    EvCode = 0x188
	KEY_VIDEO                    EvCode = 0x189
	KEY_DIRECTORY                EvCode = 0x18a
	KEY_LIST                     EvCode = 0x18b
	KEY_MEMO                     EvCode = 0x18c
	KEY_CALENDAR                 EvCode = 0x18d
	KEY_RED                      EvCode = 0x18e
	KEY_GREEN                    EvCode = 0x18f
	KEY_YELLOW                   EvCode = 0x190
	KEY_BLUE                     EvCode = 0x191
	KEY_CHANNELUP                EvCode = 0x192
	KEY_CHANNELDOWN              EvCode = 0x193
	KEY_FIRST                    EvCode = 0x194
	KEY_LAST                     EvCode = 0x195
	KEY_AB                       EvCode = 0x196
	KEY_NEXT                     EvCode = 0x197
	KEY_RESTART                  EvCode = 0x198
	KEY_SLOW                     EvCode = 0x199
	KEY_SHUFFLE                  EvCode = 0x19a
	KEY_BREAK                    EvCode = 0x19b
	KEY_PREVIOUS                 EvCode = 0x19c
	KEY_DIGITS                   EvCode = 0x19d
	KEY_TEEN                     EvCode = 0x19e
	KEY_TWEN                     EvCode = 0x19f
	KEY_VIDEOPHONE               EvCode = 0x1a0
	KEY_GAMES                    EvCode = 0x1a1
	KEY_ZOOMIN                   EvCode = 0x1a2
	KEY_ZOOMOUT                  EvCode = 0x1a3
	KEY_ZOOMRESET                EvCode = 0x1a4
	KEY_WORDPROCESSOR            EvCode = 0x1a5
	KEY_EDITOR                   EvCode = 0x1a6
	KEY_SPREADSHEET              EvCode = 0x1a7
	KEY_GRAPHICSEDITOR           EvCode = 0x1a8
	KEY_PRESENTATION             EvCode = 0x1a9
	KEY_DATABASE                 EvCode = 0x1aa
	KEY_NEWS                     EvCode = 0x1ab
	KEY_VOICEMAIL                EvCode = 0x1ac
	KEY_ADDRESSBOOK              EvCode = 0x1ad
	KEY_MESSENGER                EvCode = 0x1ae
	KEY_DISPLAYTOGGLE            EvCode = 0x1af
	KEY_BRIGHTNESS_TOGGLE        EvCode = 0x1af
	KEY_SPELLCHECK               EvCode = 0x1b0
	KEY_LOGOFF                   EvCode = 0x1b1
	KEY_DOLLAR                   EvCode = 0x1b2
	KEY_EURO                     EvCode = 0x1b3
	KEY_FRAMEBACK                EvCode = 0x1b4
	KEY_FRAMEFORWARD             EvCode = 0x1b5
	KEY_CONTEXT_MENU             EvCode = 0x1b6
	KEY_MEDIA_REPEAT             EvCode = 0x1b7
	KEY_10CHANNELSUP             EvCode = 0x1b8
	KEY_10CHANNELSDOWN           EvCode = 0x1b9
	KEY_IMAGES                   EvCode = 0x1ba
	KEY_NOTIFICATION_CENTER      EvCode = 0x1bc
	KEY_PICKUP_PHONE             EvCode = 0x1bd
	KEY_HANGUP_PHONE             EvCode = 0x1be
	KEY_LINK_PHONE               EvCode = 0x1bf
	KEY_DEL_EOL                  EvCode = 0x1c0
	KEY_DEL_EOS                  EvCode = 0x1c1
	KEY_INS_LINE                 EvCode = 0x1c2
	KEY_DEL_LINE                 EvCode = 0x1c3
	KEY_FN                       EvCode = 0x1d0
	KEY_FN_ESC                   EvCode = 0x1d1
	KEY_FN_F1                    EvCode = 0x1d2
	KEY_FN_F2                    EvCode = 0x1d3
	KEY_FN_F3                    EvCode = 0x1d4
	KEY_FN_F4                    EvCode = 0x1d5
	KEY_FN_F5                    EvCode = 0x1d6
	KEY_FN_F6                    EvCode = 0x1d7
	KEY_FN_F7                    EvCode = 0x1d8
	KEY_FN_F8                    EvCode = 0x1d9
	KEY_FN_F9                    EvCode = 0x1da
	KEY_FN_F10                   EvCode = 0x1db
	KEY_FN_F11                   EvCode = 0x1dc
	KEY_FN_F12                   EvCode = 0x1dd
	KEY_FN_1                     EvCode = 0x1de
	KEY_FN_2                     EvCode = 0x1df
	KEY_FN_D                     EvCode = 0x1e0
	KEY_FN_E                     EvCode = 0x1e1
	KEY_FN_F                     EvCode = 0x1e2
	KEY_FN_S                     EvCode = 0x1e3
	KEY_FN_B                     EvCode = 0x1e4
	KEY_FN_RIGHT_SHIFT           EvCode = 0x1e5
	KEY_BRL_DOT1                 EvCode = 0x1f1
	KEY_BRL_DOT2                 EvCode = 0x1f2
	KEY_BRL_DOT3                 EvCode = 0x1f3
	KEY_BRL_DOT4                 EvCode = 0x1f4
	KEY_BRL_DOT5                 EvCode = 0x1f5
	KEY_BRL_DOT6                 EvCode = 0x1f6
	KEY_BRL_DOT7                 EvCode = 0x1f7
	KEY_BRL_DOT8                 EvCode = 0x1f8
	KEY_BRL_DOT9                 EvCode = 0x1f9
	KEY_BRL_DOT10                EvCode = 0x1fa
	KEY_NUMERIC_0                EvCode = 0x200
	KEY_NUMERIC_1                EvCode = 0x201
	KEY_NUMERIC_2                EvCode = 0x202
	KEY_NUMERIC_3                EvCode = 0x203
	KEY_NUMERIC_4                EvCode = 0x204
	KEY_NUMERIC_5                EvCode = 0x205
	KEY_NUMERIC_6                EvCode = 0x206
	KEY_NUMERIC_7                EvCode = 0x207
	KEY_NUMERIC_8                EvCode = 0x208
	KEY_NUMERIC_9                EvCode = 0x209
	KEY_NUMERIC_STAR             EvCode = 0x20a
	KEY_NUMERIC_POUND            EvCode = 0x20b
	KEY_NUMERIC_A                EvCode = 0x20c
	KEY_NUMERIC_B                EvCode = 0x20d
	KEY_NUMERIC_C                EvCode = 0x20e
	KEY_NUMERIC_D                EvCode = 0x20f
	KEY_CAMERA_FOCUS             EvCode = 0x210
	KEY_WPS_BUTTON               EvCode = 0x211
	KEY_TOUCHPAD_TOGGLE          EvCode = 0x212
	KEY_TOUCHPAD_ON              EvCode = 0x213
	KEY_TOUCHPAD_OFF             EvCode = 0x214
	KEY_CAMERA_ZOOMIN            EvCode = 0x215
	KEY_CAMERA_ZOOMOUT           EvCode = 0x216
	KEY_CAMERA_UP                EvCode = 0x217
	KEY_CAMERA_DOWN              EvCode = 0x218
	KEY_CAMERA_LEFT              EvCode = 0x219
	KEY_CAMERA_RIGHT             EvCode = 0x21a
	KEY_ATTENDANT_ON             EvCode = 0x21b
	KEY_ATTENDANT_OFF            EvCode = 0x21c
	KEY_ATTENDANT_TOGGLE         EvCode = 0x21d
	KEY_LIGHTS_TOGGLE            EvCode = 0x21e
	BTN_DPAD_UP                  EvCode = 0x220
	BTN_DPAD_DOWN                EvCode = 0x221
	BTN_DPAD_LEFT                EvCode = 0x222
	BTN_DPAD_RIGHT               EvCode = 0x223
	BTN_GRIPL                    EvCode = 0x224
	BTN_GRIPR                    EvCode = 0x225
	BTN_GRIPL2                   EvCode = 0x226
	BTN_GRIPR2                   EvCode = 0x227
	KEY_ALS_TOGGLE               EvCode = 0x230
	KEY_ROTATE_LOCK_TOGGLE       EvCode = 0x231
	KEY_REFRESH_RATE_TOGGLE      EvCode = 0x232
	KEY_BUTTONCONFIG             EvCode = 0x240
	KEY_TASKMANAGER              EvCode = 0x241
	KEY_JOURNAL                  EvCode = 0x242
	KEY_CONTROLPANEL             EvCode = 0x243
	KEY_APPSELECT                EvCode = 0x244
	KEY_SCREENSAVER              EvCode = 0x245
	KEY_VOICECOMMAND             EvCode = 0x246
	KEY_ASSISTANT                EvCode = 0x247
	KEY_KBD_LAYOUT_NEXT          EvCode = 0x248
	KEY_EMOJI_PICKER             EvCode = 0x249
	KEY_DICTATE                  EvCode = 0x24a
	KEY_CAMERA_ACCESS_ENABLE     EvCode = 0x24b
	KEY_CAMERA_ACCESS_DISABLE    EvCode = 0x24c
	KEY_CAMERA_ACCESS_TOGGLE     EvCode = 0x24d
	KEY_ACCESSIBILITY            EvCode = 0x24e
	KEY_DO_NOT_DISTURB           EvCode = 0x24f
	KEY_BRIGHTNESS_MIN           EvCode = 0x250
	KEY_BRIGHTNESS_MAX           EvCode = 0x251
	KEY_EPRIVACY_SCREEN_ON       EvCode = 0x252
	KEY_EPRIVACY_SCREEN_OFF      EvCode = 0x253
	KEY_ACTION_ON_SELECTION      EvCode = 0x254
	KEY_CONTEXTUAL_INSERT        EvCode = 0x255
	KEY_CONTEXTUAL_QUERY         EvCode = 0x256
	KEY_KBDINPUTASSIST_PREV      EvCode = 0x260
	KEY_KBDINPUTASSIST_NEXT      EvCode = 0x261
	KEY_KBDINPUTASSIST_PREVGROUP EvCode = 0x262
	KEY_KBDINPUTASSIST_NEXTGROUP EvCode = 0x263
	KEY_KBDINPUTASSIST_ACCEPT    EvCode = 0x264
	KEY_KBDINPUTASSIST_CANCEL    EvCode = 0x265
	KEY_RIGHT_UP                 EvCode = 0x266
	KEY_RIGHT_DOWN               EvCode = 0x267
	KEY_LEFT_UP                  EvCode = 0x268
	KEY_LEFT_DOWN                EvCode = 0x269
	KEY_ROOT_MENU                EvCode = 0x26a
	KEY_MEDIA_TOP_MENU           EvCode = 0x26b
	KEY_NUMERIC_11               EvCode = 0x26c
	KEY_NUMERIC_12               EvCode = 0x26d
	KEY_AUDIO_DESC               EvCode = 0x26e
	KEY_3D_MODE                  EvCode = 0x26f
	KEY_NEXT_FAVORITE            EvCode = 0x270
	KEY_STOP_RECORD              EvCode = 0x271
	KEY_PAUSE_RECORD             EvCode = 0x272
	KEY_VOD                      EvCode = 0x273
	KEY_UNMUTE                   EvCode = 0x274
	KEY_FASTREVERSE              EvCode = 0x275
	KEY_SLOWREVERSE              EvCode = 0x276
	KEY_DATA                     EvCode = 0x277
	KEY_ONSCREEN_KEYBOARD        EvCode = 0x278
	KEY_PRIVACY_SCREEN_TOGGLE    EvCode = 0x279
	KEY_SELECTIVE_SCREENSHOT     EvCode = 0x27a
	KEY_NEXT_ELEMENT             EvCode = 0x27b
	KEY_PREVIOUS_ELEMENT         EvCode = 0x27c
	KEY_AUTOPILOT_ENGAGE_TOGGLE  EvCode = 0x27d
	KEY_MARK_WAYPOINT            EvCode = 0x27e
	KEY_SOS                      EvCode = 0x27f
	KEY_NAV_CHART                EvCode = 0x280
	KEY_FISHING_CHART            EvCode = 0x281
	KEY_SINGLE_RANGE_RADAR       EvCode = 0x282
	KEY_DUAL_RANGE_RADAR         EvCode = 0x283
	KEY_RADAR_OVERLAY            EvCode = 0x284
	KEY_TRADITIONAL_SONAR        EvCode = 0x285
	KEY_CLEARVU_SONAR            EvCode = 0x286
	KEY_SIDEVU_SONAR             EvCode = 0x287
	KEY_NAV_INFO                 EvCode = 0x288
	KEY_BRIGHTNESS_MENU          EvCode = 0x289
	KEY_MACRO1                   EvCode = 0x290
	KEY_MACRO2                   EvCode = 0x291
	KEY_MACRO3                   EvCode = 0x292
	KEY_MACRO4                   EvCode = 0x293
	KEY_MACRO5                   EvCode = 0x294
	KEY_MACRO6                   EvCode = 0x295
	KEY_MACRO7                   EvCode = 0x296
	KEY_MACRO8                   EvCode = 0x297
	KEY_MACRO9                   EvCode = 0x298
	KEY_MACRO10                  EvCode = 0x299
	KEY_MACRO11                  EvCode = 0x29a
	KEY_MACRO12                  EvCode = 0x29b
	KEY_MACRO13                  EvCode = 0x29c
	KEY_MACRO14                  EvCode = 0x29d
	KEY_MACRO15                  EvCode = 0x29e
	KEY_MACRO16                  EvCode = 0x29f
	KEY_MACRO17                  EvCode = 0x2a0
	KEY_MACRO18                  EvCode = 0x2a1
	KEY_MACRO19                  EvCode = 0x2a2
	KEY_MACRO20                  EvCode = 0x2a3
	KEY_MACRO21                  EvCode = 0x2a4
	KEY_MACRO22                  EvCode = 0x2a5
	KEY_MACRO23                  EvCode = 0x2a6
	KEY_MACRO24                  EvCode = 0x2a7
	KEY_MACRO25                  EvCode = 0x2a8
	KEY_MACRO26                  EvCode = 0x2a9
	KEY_MACRO27                  EvCode = 0x2aa
	KEY_MACRO28                  EvCode = 0x2ab
	KEY_MACRO29                  EvCode = 0x2ac
	KEY_MACRO30                  EvCode = 0x2ad
	KEY_MACRO_RECORD_START       EvCode = 0x2b0
	KEY_MACRO_RECORD_STOP        EvCode = 0x2b1
	KEY_MACRO_PRESET_CYCLE       EvCode = 0x2b2
	KEY_MACRO_PRESET1            EvCode = 0x2b3
	KEY_MACRO_PRESET2            EvCode = 0x2b4
	KEY_MACRO_PRESET3            EvCode = 0x2b5
	KEY_KBD_LCD_MENU1            EvCode = 0x2b8
	KEY_KBD_LCD_MENU2            EvCode = 0x2b9
	KEY_KBD_LCD_MENU3            EvCode = 0x2ba
	KEY_KBD_LCD_MENU4            EvCode = 0x2bb
	KEY_KBD_LCD_MENU5            EvCode = 0x2bc
	KEY_PERFORMANCE              EvCode = 0x2bd
	BTN_TRIGGER_HAPPY            EvCode = 0x2c0
	BTN_TRIGGER_HAPPY1           EvCode = 0x2c0
	BTN_TRIGGER_HAPPY2           EvCode = 0x2c1
	BTN_TRIGGER_HAPPY3           EvCode = 0x2c2
	BTN_TRIGGER_HAPPY4           EvCode = 0x2c3
	BTN_TRIGGER_HAPPY5           EvCode = 0x2c4
	BTN_TRIGGER_HAPPY6           EvCode = 0x2c5
	BTN_TRIGGER_HAPPY7           EvCode = 0x2c6
	BTN_TRIGGER_HAPPY8           EvCode = 0x2c7
	BTN_TRIGGER_HAPPY9           EvCode = 0x2c8
	BTN_TRIGGER_HAPPY10          EvCode = 0x2c9
	BTN_TRIGGER_HAPPY11          EvCode = 0x2ca
	BTN_TRIGGER_HAPPY12          EvCode = 0x2cb
	BTN_TRIGGER_HAPPY13          EvCode = 0x2cc
	BTN_TRIGGER_HAPPY14          EvCode = 0x2cd
	BTN_TRIGGER_HAPPY15          EvCode = 0x2ce
	BTN_TRIGGER_HAPPY16          EvCode = 0x2cf
	BTN_TRIGGER_HAPPY17          EvCode = 0x2d0
	BTN_TRIGGER_HAPPY18          EvCode = 0x2d1
	BTN_TRIGGER_HAPPY19          EvCode = 0x2d2
	BTN_TRIGGER_HAPPY20          EvCode = 0x2d3
	BTN_TRIGGER_HAPPY21          EvCode = 0x2d4
	BTN_TRIGGER_HAPPY22          EvCode = 0x2d5
	BTN_TRIGGER_HAPPY23          EvCode = 0x2d6
	BTN_TRIGGER_HAPPY24          EvCode = 0x2d7
	BTN_TRIGGER_HAPPY25          EvCode = 0x2d8
	BTN_TRIGGER_HAPPY26          EvCode = 0x2d9
	BTN_TRIGGER_HAPPY27          EvCode = 0x2da
	BTN_TRIGGER_HAPPY28          EvCode = 0x2db
	BTN_TRIGGER_HAPPY29          EvCode = 0x2dc
	BTN_TRIGGER_HAPPY30          EvCode = 0x2dd
	BTN_TRIGGER_HAPPY31          EvCode = 0x2de
	BTN_TRIGGER_HAPPY32          EvCode = 0x2df
	BTN_TRIGGER_HAPPY33          EvCode = 0x2e0
	BTN_TRIGGER_HAPPY34          EvCode = 0x2e1
	BTN_TRIGGER_HAPPY35          EvCode = 0x2e2
	BTN_TRIGGER_HAPPY36          EvCode = 0x2e3
	BTN_TRIGGER_HAPPY37          EvCode = 0x2e4
	BTN_TRIGGER_HAPPY38          EvCode = 0x2e5
	BTN_TRIGGER_HAPPY39          EvCode = 0x2e6
	BTN_TRIGGER_HAPPY40          EvCode = 0x2e7
	KEY_MIN_INTERESTING          EvCode = 0x71
	KEY_MAX                      EvCode = 0x2ff
	KEY_CNT                      EvCode = 0x300
	LED_NUML                     EvCode = 0x0
	LED_CAPSL                    EvCode = 0x1
	LED_SCROLLL                  EvCode = 0x2
	LED_COMPOSE                  EvCode = 0x3
	LED_KANA                     EvCode = 0x4
	LED_SLEEP                    EvCode = 0x5
	LED_SUSPEND                  EvCode = 0x6
	LED_MUTE                     EvCode = 0x7
	LED_MISC                     EvCode = 0x8
	LED_MAIL                     EvCode = 0x9
	LED_CHARGING                 EvCode = 0xa
	LED_MAX                      EvCode = 0xf
	LED_CNT                      EvCode = 0x10
	MSC_SERIAL                   EvCode = 0x0
	MSC_PULSELED                 EvCode = 0x1
	MSC_GESTURE                  EvCode = 0x2
	MSC_RAW                      EvCode = 0x3
	MSC_SCAN                     EvCode = 0x4
	MSC_TIMESTAMP                EvCode = 0x5
	MSC_MAX                      EvCode = 0x7
	MSC_CNT                      EvCode = 0x8
	REL_X                        EvCode = 0x0
	REL_Y                        EvCode = 0x1
	REL_Z                        EvCode = 0x2
	REL_RX                       EvCode = 0x3
	REL_RY                       EvCode = 0x4
	REL_RZ                       EvCode = 0x5
	REL_HWHEEL                   EvCode = 0x6
	REL_DIAL                     EvCode = 0x7
	REL_WHEEL                    EvCode = 0x8
	REL_MISC                     EvCode = 0x9
	REL_RESERVED                 EvCode = 0xa
	REL_WHEEL_HI_RES             EvCode = 0xb
	REL_HWHEEL_HI_RES            EvCode = 0xc
	REL_MAX                      EvCode = 0xf
	REL_CNT                      EvCode = 0x10
	REP_DELAY                    EvCode = 0x0
	REP_PERIOD                   EvCode = 0x1
	REP_MAX                      EvCode = 0x1
	REP_CNT                      EvCode = 0x2
	SND_CLICK                    EvCode = 0x0
	SND_BELL                     EvCode = 0x1
	SND_TONE                     EvCode = 0x2
	SND_MAX                      EvCode = 0x7
	SND_CNT                      EvCode = 0x8
	SND_PROFILE_SILENT           EvCode = 0x0
	SND_PROFILE_VIBRATE          EvCode = 0x1
	SND_PROFILE_RING             EvCode = 0x2
	SW_LID                       EvCode = 0x0
	SW_TABLET_MODE               EvCode = 0x1
	SW_HEADPHONE_INSERT          EvCode = 0x2
	SW_RFKILL_ALL                EvCode = 0x3
	SW_RADIO                     EvCode = 0x3
	SW_MICROPHONE_INSERT         EvCode = 0x4
	SW_DOCK                      EvCode = 0x5
	SW_LINEOUT_INSERT            EvCode = 0x6
	SW_JACK_PHYSICAL_INSERT      EvCode = 0x7
	SW_VIDEOOUT_INSERT           EvCode = 0x8
	SW_CAMERA_LENS_COVER         EvCode = 0x9
	SW_KEYPAD_SLIDE              EvCode = 0xa
	SW_FRONT_PROXIMITY           EvCode = 0xb
	SW_ROTATE_LOCK               EvCode = 0xc
	SW_LINEIN_INSERT             EvCode = 0xd
	SW_MUTE_DEVICE               EvCode = 0xe
	SW_PEN_INSERTED              EvCode = 0xf
	SW_MACHINE_COVER             EvCode = 0x10
	SW_USB_INSERT                EvCode = 0x11
	SW_MAX                       EvCode = 0x11
	SW_CNT                       EvCode = 0x12
	SYN_REPORT                   EvCode = 0x0
	SYN_CONFIG                   EvCode = 0x1
	SYN_MT_REPORT                EvCode = 0x2
	SYN_DROPPED                  EvCode = 0x3
	SYN_MAX                      EvCode = 0xf
	SYN_CNT                      EvCode = 0x10
)

const (
	BUS_PCI         BusType = 0x1
	BUS_ISAPNP      BusType = 0x2
	BUS_USB         BusType = 0x3
	BUS_HIL         BusType = 0x4
	BUS_BLUETOOTH   BusType = 0x5
	BUS_VIRTUAL     BusType = 0x6
	BUS_ISA         BusType = 0x10
	BUS_I8042       BusType = 0x11
	BUS_XTKBD       BusType = 0x12
	BUS_RS232       BusType = 0x13
	BUS_GAMEPORT    BusType = 0x14
	BUS_PARPORT     BusType = 0x15
	BUS_AMIGA       BusType = 0x16
	BUS_ADB         BusType = 0x17
	BUS_I2C         BusType = 0x18
	BUS_HOST        BusType = 0x19
	BUS_GSC         BusType = 0x1a
	BUS_ATARI       BusType = 0x1b
	BUS_SPI         BusType = 0x1c
	BUS_RMI         BusType = 0x1d
	BUS_CEC         BusType = 0x1e
	BUS_INTEL_ISHTP BusType = 0x1f
	BUS_AMD_SFH     BusType = 0x20
	BUS_SDW         BusType = 0x21
)

const (
	INPUT_PROP_POINTER        InputProp = 0x0
	INPUT_PROP_DIRECT         InputProp = 0x1
	INPUT_PROP_BUTTONPAD      InputProp = 0x2
	INPUT_PROP_SEMI_MT        InputProp = 0x3
	INPUT_PROP_TOPBUTTONPAD   InputProp = 0x4
	INPUT_PROP_POINTING_STICK InputProp = 0x5
	INPUT_PROP_ACCELEROMETER  InputProp = 0x6
	INPUT_PROP_PRESSUREPAD    InputProp = 0x7
	INPUT_PROP_MAX            InputProp = 0x1f
	INPUT_PROP_CNT            InputProp = 0x20
)

var evTypeNames = map[EvType]string{
	EV_SYN:       "EV_SYN",
	EV_KEY:       "EV_KEY",
	EV_REL:       "EV_REL",
	EV_ABS:       "EV_ABS",
	EV_MSC:       "EV_MSC",
	EV_SW:        "EV_SW",
	EV_LED:       "EV_LED",
	EV_SND:       "EV_SND",
	EV_REP:       "EV_REP",
	EV_FF:        "EV_FF",
	EV_PWR:       "EV_PWR",
	EV_FF_STATUS: "EV_FF_STATUS",
}

var evTypeByName = map[string]EvType{
	"EV_SYN":       EV_SYN,
	"EV_KEY":       EV_KEY,
	"EV_REL":       EV_REL,
	"EV_ABS":       EV_ABS,
	"EV_MSC":       EV_MSC,
	"EV_SW":        EV_SW,
	"EV_LED":       EV_LED,
	"EV_SND":       EV_SND,
	"EV_REP":       EV_REP,
	"EV_FF":        EV_FF,
	"EV_PWR":       EV_PWR,
	"EV_FF_STATUS": EV_FF_STATUS,
}

var evCodeNames = map[EvType]map[EvCode]string{
	EV_ABS: {
		0x0:  "ABS_X",
		0x1:  "ABS_Y",
		0x2:  "ABS_Z",
		0x3:  "ABS_RX",
		0x4:  "ABS_RY",
		0x5:  "ABS_RZ",
		0x6:  "ABS_THROTTLE",
		0x7:  "ABS_RUDDER",
		0x8:  "ABS_WHEEL",
		0x9:  "ABS_GAS",
		0xa:  "ABS_BRAKE",
		0x10: "ABS_HAT0X",
		0x11: "ABS_HAT0Y",
		0x12: "ABS_HAT1X",
		0x13: "ABS_HAT1Y",
		0x14: "ABS_HAT2X",
		0x15: "ABS_HAT2Y",
		0x16: "ABS_HAT3X",
		0x17: "ABS_HAT3Y",
		0x18: "ABS_PRESSURE",
		0x19: "ABS_DISTANCE",
		0x1a: "ABS_TILT_X",
		0x1b: "ABS_TILT_Y",
		0x1c: "ABS_TOOL_WIDTH",
		0x20: "ABS_VOLUME",
		0x21: "ABS_PROFILE",
		0x22: "ABS_SND_PROFILE",
		0x28: "ABS_MISC",
		0x2e: "ABS_RESERVED",
		0x2f: "ABS_MT_SLOT",
		0x30: "ABS_MT_TOUCH_MAJOR",
		0x31: "ABS_MT_TOUCH_MINOR",
		0x32: "ABS_MT_WIDTH_MAJOR",
		0x33: "ABS_MT_WIDTH_MINOR",
		0x34: "ABS_MT_ORIENTATION",
		0x35: "ABS_MT_POSITION_X",
		0x36: "ABS_MT_POSITION_Y",
		0x37: "ABS_MT_TOOL_TYPE",
		0x38: "ABS_MT_BLOB_ID",
		0x39: "ABS_MT_TRACKING_ID",
		0x3a: "ABS_MT_PRESSURE",
		0x3b: "ABS_MT_DISTANCE",
		0x3c: "ABS_MT_TOOL_X",
		0x3d: "ABS_MT_TOOL_Y",
	},
	EV_KEY: {
		0x0:   "KEY_RESERVED",
		0x1:   "KEY_ESC",
		0x2:   "KEY_1",
		0x3:   "KEY_2",
		0x4:   "KEY_3",
		0x5:   "KEY_4",
		0x6:   "KEY_5",
		0x7:   "KEY_6",
		0x8:   "KEY_7",
		0x9:   "KEY_8",
		0xa:   "KEY_9",
		0xb:   "KEY_0",
		0xc:   "KEY_MINUS",
		0xd:   "KEY_EQUAL",
		0xe:   "KEY_BACKSPACE",
		0xf:   "KEY_TAB",
		0x10:  "KEY_Q",
		0x11:  "KEY_W",
		0x12:  "KEY_E",
		0x13:  "KEY_R",
		0x14:  "KEY_T",
		0x15:  "KEY_Y",
		0x16:  "KEY_U",
		0x17:  "KEY_I",
		0x18:  "KEY_O",
		0x19:  "KEY_P",
		0x1a:  "KEY_LEFTBRACE",
		0x1b:  "KEY_RIGHTBRACE",
		0x1c:  "KEY_ENTER",
		0x1d:  "KEY_LEFTCTRL",
		0x1e:  "KEY_A",
		0x1f:  "KEY_S",
		0x20:  "KEY_D",
		0x21:  "KEY_F",
		0x22:  "KEY_G",
		0x23:  "KEY_H",
		0x24:  "KEY_J",
		0x25:  "KEY_K",
		0x26:  "KEY_L",
		0x27:  "KEY_SEMICOLON",
		0x28:  "KEY_APOSTROPHE",
		0x29:  "KEY_GRAVE",
		0x2a:  "KEY_LEFTSHIFT",
		0x2b:  "KEY_BACKSLASH",
		0x2c:  "KEY_Z",
		0x2d:  "KEY_X",
		0x2e:  "KEY_C",
		0x2f:  "KEY_V",
		0x30:  "KEY_B",
		0x31:  "KEY_N",
		0x32:  "KEY_M",
		0x33:  "KEY_COMMA",
		0x34:  "KEY_DOT",
		0x35:  "KEY_SLASH",
		0x36:  "KEY_RIGHTSHIFT",
		0x37:  "KEY_KPASTERISK",
		0x38:  "KEY_LEFTALT",
		0x39:  "KEY_SPACE",
		0x3a:  "KEY_CAPSLOCK",
		0x3b:  "KEY_F1",
		0x3c:  "KEY_F2",
		0x3d:  "KEY_F3",
		0x3e:  "KEY_F4",
		0x3f:  "KEY_F5",
		0x40:  "KEY_F6",
		0x41:  "KEY_F7",
		0x42:  "KEY_F8",
		0x43:  "KEY_F9",
		0x44:  "KEY_F10",
		0x45:  "KEY_NUMLOCK",
		0x46:  "KEY_SCROLLLOCK",
		0x47:  "KEY_KP7",
		0x48:  "KEY_KP8",
		0x49:  "KEY_KP9",
		0x4a:  "KEY_KPMINUS",
		0x4b:  "KEY_KP4",
		0x4c:  "KEY_KP5",
		0x4d:  "KEY_KP6",
		0x4e:  "KEY_KPPLUS",
		0x4f:  "KEY_KP1",
		0x50:  "KEY_KP2",
		0x51:  "KEY_KP3",
		0x52:  "KEY_KP0",
		0x53:  "KEY_KPDOT",
		0x55:  "KEY_ZENKAKUHANKAKU",
		0x56:  "KEY_102ND",
		0x57:  "KEY_F11",
		0x58:  "KEY_F12",
		0x59:  "KEY_RO",
		0x5a:  "KEY_KATAKANA",
		0x5b:  "KEY_HIRAGANA",
		0x5c:  "KEY_HENKAN",
		0x5d:  "KEY_KATAKANAHIRAGANA",
		0x5e:  "KEY_MUHENKAN",
		0x5f:  "KEY_KPJPCOMMA",
		0x60:  "KEY_KPENTER",
		0x61:  "KEY_RIGHTCTRL",
		0x62:  "KEY_KPSLASH",
		0x63:  "KEY_SYSRQ",
		0x64:  "KEY_RIGHTALT",
		0x65:  "KEY_LINEFEED",
		0x66:  "KEY_HOME",
		0x67:  "KEY_UP",
		0x68:  "KEY_PAGEUP",
		0x69:  "KEY_LEFT",
		0x6a:  "KEY_RIGHT",
		0x6b:  "KEY_END",
		0x6c:  "KEY_DOWN",
		0x6d:  "KEY_PAGEDOWN",
		0x6e:  "KEY_INSERT",
		0x6f:  "KEY_DELETE",
		0x70:  "KEY_MACRO",
		0x71:  "KEY_MUTE",
		0x72:  "KEY_VOLUMEDOWN",
		0x73:  "KEY_VOLUMEUP",
		0x74:  "KEY_POWER",
		0x75:  "KEY_KPEQUAL",
		0x76:  "KEY_KPPLUSMINUS",
		0x77:  "KEY_PAUSE",
		0x78:  "KEY_SCALE",
		0x79:  "KEY_KPCOMMA",
		0x7a:  "KEY_HANGEUL",
		0x7b:  "KEY_HANJA",
		0x7c:  "KEY_YEN",
		0x7d:  "KEY_LEFTMETA",
		0x7e:  "KEY_RIGHTMETA",
		0x7f:  "KEY_COMPOSE",
		0x80:  "KEY_STOP",
		0x81:  "KEY_AGAIN",
		0x82:  "KEY_PROPS",
		0x83:  "KEY_UNDO",
		0x84:  "KEY_FRONT",
		0x85:  "KEY_COPY",
		0x86:  "KEY_OPEN",
		0x87:  "KEY_PASTE",
		0x88:  "KEY_FIND",
		0x89:  "KEY_CUT",
		0x8a:  "KEY_HELP",
		0x8b:  "KEY_MENU",
		0x8c:  "KEY_CALC",
		0x8d:  "KEY_SETUP",
		0x8e:  "KEY_SLEEP",
		0x8f:  "KEY_WAKEUP",
		0x90:  "KEY_FILE",
		0x91:  "KEY_SENDFILE",
		0x92:  "KEY_DELETEFILE",
		0x93:  "KEY_XFER",
		0x94:  "KEY_PROG1",
		0x95:  "KEY_PROG2",
		0x96:  "KEY_WWW",
		0x97:  "KEY_MSDOS",
		0x98:  "KEY_COFFEE",
		0x99:  "KEY_ROTATE_DISPLAY",
		0x9a:  "KEY_CYCLEWINDOWS",
		0x9b:  "KEY_MAIL",
		0x9c:  "KEY_BOOKMARKS",
		0x9d:  "KEY_COMPUTER",
		0x9e:  "KEY_BACK",
		0x9f:  "KEY_FORWARD",
		0xa0:  "KEY_CLOSECD",
		0xa1:  "KEY_EJECTCD",
		0xa2:  "KEY_EJECTCLOSECD",
		0xa3:  "KEY_NEXTSONG",
		0xa4:  "KEY_PLAYPAUSE",
		0xa5:  "KEY_PREVIOUSSONG",
		0xa6:  "KEY_STOPCD",
		0xa7:  "KEY_RECORD",
		0xa8:  "KEY_REWIND",
		0xa9:  "KEY_PHONE",
		0xaa:  "KEY_ISO",
		0xab:  "KEY_CONFIG",
		0xac:  "KEY_HOMEPAGE",
		0xad:  "KEY_REFRESH",
		0xae:  "KEY_EXIT",
		0xaf:  "KEY_MOVE",
		0xb0:  "KEY_EDIT",
		0xb1:  "KEY_SCROLLUP",
		0xb2:  "KEY_SCROLLDOWN",
		0xb3:  "KEY_KPLEFTPAREN",
		0xb4:  "KEY_KPRIGHTPAREN",
		0xb5:  "KEY_NEW",
		0xb6:  "KEY_REDO",
		0xb7:  "KEY_F13",
		0xb8:  "KEY_F14",
		0xb9:  "KEY_F15",
		0xba:  "KEY_F16",
		0xbb:  "KEY_F17",
		0xbc:  "KEY_F18",
		0xbd:  "KEY_F19",
		0xbe:  "KEY_F20",
		0xbf:  "KEY_F21",
		0xc0:  "KEY_F22",
		0xc1:  "KEY_F23",
		0xc2:  "KEY_F24",
		0xc8:  "KEY_PLAYCD",
		0xc9:  "KEY_PAUSECD",
		0xca:  "KEY_PROG3",
		0xcb:  "KEY_PROG4",
		0xcc:  "KEY_ALL_APPLICATIONS",
		0xcd:  "KEY_SUSPEND",
		0xce:  "KEY_CLOSE",
		0xcf:  "KEY_PLAY",
		0xd0:  "KEY_FASTFORWARD",
		0xd1:  "KEY_BASSBOOST",
		0xd2:  "KEY_PRINT",
		0xd3:  "KEY_HP",
		0xd4:  "KEY_CAMERA",
		0xd5:  "KEY_SOUND",
		0xd6:  "KEY_QUESTION",
		0xd7:  "KEY_EMAIL",
		0xd8:  "KEY_CHAT",
		0xd9:  "KEY_SEARCH",
		0xda:  "KEY_CONNECT",
		0xdb:  "KEY_FINANCE",
		0xdc:  "KEY_SPORT",
		0xdd:  "KEY_SHOP",
		0xde:  "KEY_ALTERASE",
		0xdf:  "KEY_CANCEL",
		0xe0:  "KEY_BRIGHTNESSDOWN",
		0xe1:  "KEY_BRIGHTNESSUP",
		0xe2:  "KEY_MEDIA",
		0xe3:  "KEY_SWITCHVIDEOMODE",
		0xe4:  "KEY_KBDILLUMTOGGLE",
		0xe5:  "KEY_KBDILLUMDOWN",
		0xe6:  "KEY_KBDILLUMUP",
		0xe7:  "KEY_SEND",
		0xe8:  "KEY_REPLY",
		0xe9:  "KEY_FORWARDMAIL",
		0xea:  "KEY_SAVE",
		0xeb:  "KEY_DOCUMENTS",
		0xec:  "KEY_BATTERY",
		0xed:  "KEY_BLUETOOTH",
		0xee:  "KEY_WLAN",
		0xef:  "KEY_UWB",
		0xf0:  "KEY_UNKNOWN",
		0xf1:  "KEY_VIDEO_NEXT",
		0xf2:  "KEY_VIDEO_PREV",
		0xf3:  "KEY_BRIGHTNESS_CYCLE",
		0xf4:  "KEY_BRIGHTNESS_AUTO",
		0xf5:  "KEY_DISPLAY_OFF",
		0xf6:  "KEY_WWAN",
		0xf7:  "KEY_RFKILL",
		0xf8:  "KEY_MICMUTE",
		0x100: "BTN_MISC",
		0x101: "BTN_1",
		0x102: "BTN_2",
		0x103: "BTN_3",
		0x104: "BTN_4",
		0x105: "BTN_5",
		0x106: "BTN_6",
		0x107: "BTN_7",
		0x108: "BTN_8",
		0x109: "BTN_9",
		0x110: "BTN_MOUSE",
		0x111: "BTN_RIGHT",
		0x112: "BTN_MIDDLE",
		0x113: "BTN_SIDE",
		0x114: "BTN_EXTRA",
		0x115: "BTN_FORWARD",
		0x116: "BTN_BACK",
		0x117: "BTN_TASK",
		0x120: "BTN_JOYSTICK",
		0x121: "BTN_THUMB",
		0x122: "BTN_THUMB2",
		0x123: "BTN_TOP",
		0x124: "BTN_TOP2",
		0x125: "BTN_PINKIE",
		0x126: "BTN_BASE",
		0x127: "BTN_BASE2",
		0x128: "BTN_BASE3",
		0x129: "BTN_BASE4",
		0x12a: "BTN_BASE5",
		0x12b: "BTN_BASE6",
		0x12f: "BTN_DEAD",
		0x130: "BTN_GAMEPAD",
		0x131: "BTN_EAST",
		0x132: "BTN_C",
		0x133: "BTN_NORTH",
		0x134: "BTN_WEST",
		0x135: "BTN_Z",
		0x136: "BTN_TL",
		0x137: "BTN_TR",
		0x138: "BTN_TL2",
		0x139: "BTN_TR2",
		0x13a: "BTN_SELECT",
		0x13b: "BTN_START",
		0x13c: "BTN_MODE",
		0x13d: "BTN_THUMBL",
		0x13e: "BTN_THUMBR",
		0x140: "BTN_DIGI",
		0x141: "BTN_TOOL_RUBBER",
		0x142: "BTN_TOOL_BRUSH",
		0x143: "BTN_TOOL_PENCIL",
		0x144: "BTN_TOOL_AIRBRUSH",
		0x145: "BTN_TOOL_FINGER",
		0x146: "BTN_TOOL_MOUSE",
		0x147: "BTN_TOOL_LENS",
		0x148: "BTN_TOOL_QUINTTAP",
		0x149: "BTN_STYLUS3",
		0x14a: "BTN_TOUCH",
		0x14b: "BTN_STYLUS",
		0x14c: "BTN_STYLUS2",
		0x14d: "BTN_TOOL_DOUBLETAP",
		0x14e: "BTN_TOOL_TRIPLETAP",
		0x14f: "BTN_TOOL_QUADTAP",
		0x150: "BTN_WHEEL",
		0x151: "BTN_GEAR_UP",
		0x160: "KEY_OK",
		0x161: "KEY_SELECT",
		0x162: "KEY_GOTO",
		0x163: "KEY_CLEAR",
		0x164: "KEY_POWER2",
		0x165: "KEY_OPTION",
		0x166: "KEY_INFO",
		0x167: "KEY_TIME",
		0x168: "KEY_VENDOR",
		0x169: "KEY_ARCHIVE",
		0x16a: "KEY_PROGRAM",
		0x16b: "KEY_CHANNEL",
		0x16c: "KEY_FAVORITES",
		0x16d: "KEY_EPG",
		0x16e: "KEY_PVR",
		0x16f: "KEY_MHP",
		0x170: "KEY_LANGUAGE",
		0x171: "KEY_TITLE",
		0x172: "KEY_SUBTITLE",
		0x173: "KEY_ANGLE",
		0x174: "KEY_FULL_SCREEN",
		0x175: "KEY_MODE",
		0x176: "KEY_KEYBOARD",
		0x177: "KEY_ASPECT_RATIO",
		0x178: "KEY_PC",
		0x179: "KEY_TV",
		0x17a: "KEY_TV2",
		0x17b: "KEY_VCR",
		0x17c: "KEY_VCR2",
		0x17d: "KEY_SAT",
		0x17e: "KEY_SAT2",
		0x17f: "KEY_CD",
		0x180: "KEY_TAPE",
		0x181: "KEY_RADIO",
		0x182: "KEY_TUNER",
		0x183: "KEY_PLAYER",
		0x184: "KEY_TEXT",
		0x185: "KEY_DVD",
		0x186: "KEY_AUX",
		0x187: "KEY_MP3",
		0x188: "KEY_AUDIO",
		0x189: "KEY_VIDEO",
		0x18a: "KEY_DIRECTORY",
		0x18b: "KEY_LIST",
		0x18c: "KEY_MEMO",
		0x18d: "KEY_CALENDAR",
		0x18e: "KEY_RED",
		0x18f: "KEY_GREEN",
		0x190: "KEY_YELLOW",
		0x191: "KEY_BLUE",
		0x192: "KEY_CHANNELUP",
		0x193: "KEY_CHANNELDOWN",
		0x194: "KEY_FIRST",
		0x195: "KEY_LAST",
		0x196: "KEY_AB",
		0x197: "KEY_NEXT",
		0x198: "KEY_RESTART",
		0x199: "KEY_SLOW",
		0x19a: "KEY_SHUFFLE",
		0x19b: "KEY_BREAK",
		0x19c: "KEY_PREVIOUS",
		0x19d: "KEY_DIGITS",
		0x19e: "KEY_TEEN",
		0x19f: "KEY_TWEN",
		0x1a0: "KEY_VIDEOPHONE",
		0x1a1: "KEY_GAMES",
		0x1a2: "KEY_ZOOMIN",
		0x1a3: "KEY_ZOOMOUT",
		0x1a4: "KEY_ZOOMRESET",
		0x1a5: "KEY_WORDPROCESSOR",
		0x1a6: "KEY_EDITOR",
		0x1a7: "KEY_SPREADSHEET",
		0x1a8: "KEY_GRAPHICSEDITOR",
		0x1a9: "KEY_PRESENTATION",
		0x1aa: "KEY_DATABASE",
		0x1ab: "KEY_NEWS",
		0x1ac: "KEY_VOICEMAIL",
		0x1ad: "KEY_ADDRESSBOOK",
		0x1ae: "KEY_MESSENGER",
		0x1af: "KEY_DISPLAYTOGGLE",
		0x1b0: "KEY_SPELLCHECK",
		0x1b1: "KEY_LOGOFF",
		0x1b2: "KEY_DOLLAR",
		0x1b3: "KEY_EURO",
		0x1b4: "KEY_FRAMEBACK",
		0x1b5: "KEY_FRAMEFORWARD",
		0x1b6: "KEY_CONTEXT_MENU",
		0x1b7: "KEY_MEDIA_REPEAT",
		0x1b8: "KEY_10CHANNELSUP",
		0x1b9: "KEY_10CHANNELSDOWN",
		0x1ba: "KEY_IMAGES",
		0x1bc: "KEY_NOTIFICATION_CENTER",
		0x1bd: "KEY_PICKUP_PHONE",
		0x1be: "KEY_HANGUP_PHONE",
		0x1bf: "KEY_LINK_PHONE",
		0x1c0: "KEY_DEL_EOL",
		0x1c1: "KEY_DEL_EOS",
		0x1c2: "KEY_INS_LINE",
		0x1c3: "KEY_DEL_LINE",
		0x1d0: "KEY_FN",
		0x1d1: "KEY_FN_ESC",
		0x1d2: "KEY_FN_F1",
		0x1d3: "KEY_FN_F2",
		0x1d4: "KEY_FN_F3",
		0x1d5: "KEY_FN_F4",
		0x1d6: "KEY_FN_F5",
		0x1d7: "KEY_FN_F6",
		0x1d8: "KEY_FN_F7",
		0x1d9: "KEY_FN_F8",
		0x1da: "KEY_FN_F9",
		0x1db: "KEY_FN_F10",
		0x1dc: "KEY_FN_F11",
		0x1dd: "KEY_FN_F12",
		0x1de: "KEY_FN_1",
		0x1df: "KEY_FN_2",
		0x1e0: "KEY_FN_D",
		0x1e1: "KEY_FN_E",
		0x1e2: "KEY_FN_F",
		0x1e3: "KEY_FN_S",
		0x1e4: "KEY_FN_B",
		0x1e5: "KEY_FN_RIGHT_SHIFT",
		0x1f1: "KEY_BRL_DOT1",
		0x1f2: "KEY_BRL_DOT2",
		0x1f3: "KEY_BRL_DOT3",
		0x1f4: "KEY_BRL_DOT4",
		0x1f5: "KEY_BRL_DOT5",
		0x1f6: "KEY_BRL_DOT6",
		0x1f7: "KEY_BRL_DOT7",
		0x1f8: "KEY_BRL_DOT8",
		0x1f9: "KEY_BRL_DOT9",
		0x1fa: "KEY_BRL_DOT10",
		0x200: "KEY_NUMERIC_0",
		0x201: "KEY_NUMERIC_1",
		0x202: "KEY_NUMERIC_2",
		0x203: "KEY_NUMERIC_3",
		0x204: "KEY_NUMERIC_4",
		0x205: "KEY_NUMERIC_5",
		0x206: "KEY_NUMERIC_6",
		0x207: "KEY_NUMERIC_7",
		0x208: "KEY_NUMERIC_8",
		0x209: "KEY_NUMERIC_9",
		0x20a: "KEY_NUMERIC_STAR",
		0x20b: "KEY_NUMERIC_POUND",
		0x20c: "KEY_NUMERIC_A",
		0x20d: "KEY_NUMERIC_B",
		0x20e: "KEY_NUMERIC_C",
		0x20f: "KEY_NUMERIC_D",
		0x210: "KEY_CAMERA_FOCUS",
		0x211: "KEY_WPS_BUTTON",
		0x212: "KEY_TOUCHPAD_TOGGLE",
		0x213: "KEY_TOUCHPAD_ON",
		0x214: "KEY_TOUCHPAD_OFF",
		0x215: "KEY_CAMERA_ZOOMIN",
		0x216: "KEY_CAMERA_ZOOMOUT",
		0x217: "KEY_CAMERA_UP",
		0x218: "KEY_CAMERA_DOWN",
		0x219: "KEY_CAMERA_LEFT",
		0x21a: "KEY_CAMERA_RIGHT",
		0x21b: "KEY_ATTENDANT_ON",
		0x21c: "KEY_ATTENDANT_OFF",
		0x21d: "KEY_ATTENDANT_TOGGLE",
		0x21e: "KEY_LIGHTS_TOGGLE",
		0x220: "BTN_DPAD_UP",
		0x221: "BTN_DPAD_DOWN",
		0x222: "BTN_DPAD_LEFT",
		0x223: "BTN_DPAD_RIGHT",
		0x224: "BTN_GRIPL",
		0x225: "BTN_GRIPR",
		0x226: "BTN_GRIPL2",
		0x227: "BTN_GRIPR2",
		0x230: "KEY_ALS_TOGGLE",
		0x231: "KEY_ROTATE_LOCK_TOGGLE",
		0x232: "KEY_REFRESH_RATE_TOGGLE",
		0x240: "KEY_BUTTONCONFIG",
		0x241: "KEY_TASKMANAGER",
		0x242: "KEY_JOURNAL",
		0x243: "KEY_CONTROLPANEL",
		0x244: "KEY_APPSELECT",
		0x245: "KEY_SCREENSAVER",
		0x246: "KEY_VOICECOMMAND",
		0x247: "KEY_ASSISTANT",
		0x248: "KEY_KBD_LAYOUT_NEXT",
		0x249: "KEY_EMOJI_PICKER",
		0x24a: "KEY_DICTATE",
		0x24b: "KEY_CAMERA_ACCESS_ENABLE",
		0x24c: "KEY_CAMERA_ACCESS_DISABLE",
		0x24d: "KEY_CAMERA_ACCESS_TOGGLE",
		0x24e: "KEY_ACCESSIBILITY",
		0x24f: "KEY_DO_NOT_DISTURB",
		0x250: "KEY_BRIGHTNESS_MIN",
		0x252: "KEY_EPRIVACY_SCREEN_ON",
		0x253: "KEY_EPRIVACY_SCREEN_OFF",
		0x254: "KEY_ACTION_ON_SELECTION",
		0x255: "KEY_CONTEXTUAL_INSERT",
		0x256: "KEY_CONTEXTUAL_QUERY",
		0x260: "KEY_KBDINPUTASSIST_PREV",
		0x261: "KEY_KBDINPUTASSIST_NEXT",
		0x262: "KEY_KBDINPUTASSIST_PREVGROUP",
		0x263: "KEY_KBDINPUTASSIST_NEXTGROUP",
		0x264: "KEY_KBDINPUTASSIST_ACCEPT",
		0x265: "KEY_KBDINPUTASSIST_CANCEL",
		0x266: "KEY_RIGHT_UP",
		0x267: "KEY_RIGHT_DOWN",
		0x268: "KEY_LEFT_UP",
		0x269: "KEY_LEFT_DOWN",
		0x26a: "KEY_ROOT_MENU",
		0x26b: "KEY_MEDIA_TOP_MENU",
		0x26c: "KEY_NUMERIC_11",
		0x26d: "KEY_NUMERIC_12",
		0x26e: "KEY_AUDIO_DESC",
		0x26f: "KEY_3D_MODE",
		0x270: "KEY_NEXT_FAVORITE",
		0x271: "KEY_STOP_RECORD",
		0x272: "KEY_PAUSE_RECORD",
		0x273: "KEY_VOD",
		0x274: "KEY_UNMUTE",
		0x275: "KEY_FASTREVERSE",
		0x276: "KEY_SLOWREVERSE",
		0x277: "KEY_DATA",
		0x278: "KEY_ONSCREEN_KEYBOARD",
		0x279: "KEY_PRIVACY_SCREEN_TOGGLE",
		0x27a: "KEY_SELECTIVE_SCREENSHOT",
		0x27b: "KEY_NEXT_ELEMENT",
		0x27c: "KEY_PREVIOUS_ELEMENT",
		0x27d: "KEY_AUTOPILOT_ENGAGE_TOGGLE",
		0x27e: "KEY_MARK_WAYPOINT",
		0x27f: "KEY_SOS",
		0x280: "KEY_NAV_CHART",
		0x281: "KEY_FISHING_CHART",
		0x282: "KEY_SINGLE_RANGE_RADAR",
		0x283: "KEY_DUAL_RANGE_RADAR",
		0x284: "KEY_RADAR_OVERLAY",
		0x285: "KEY_TRADITIONAL_SONAR",
		0x286: "KEY_CLEARVU_SONAR",
		0x287: "KEY_SIDEVU_SONAR",
		0x288: "KEY_NAV_INFO",
		0x289: "KEY_BRIGHTNESS_MENU",
		0x290: "KEY_MACRO1",
		0x291: "KEY_MACRO2",
		0x292: "KEY_MACRO3",
		0x293: "KEY_MACRO4",
		0x294: "KEY_MACRO5",
		0x295: "KEY_MACRO6",
		0x296: "KEY_MACRO7",
		0x297: "KEY_MACRO8",
		0x298: "KEY_MACRO9",
		0x299: "KEY_MACRO10",
		0x29a: "KEY_MACRO11",
		0x29b: "KEY_MACRO12",
		0x29c: "KEY_MACRO13",
		0x29d: "KEY_MACRO14",
		0x29e: "KEY_MACRO15",
		0x29f: "KEY_MACRO16",
		0x2a0: "KEY_MACRO17",
		0x2a1: "KEY_MACRO18",
		0x2a2: "KEY_MACRO19",
		0x2a3: "KEY_MACRO20",
		0x2a4: "KEY_MACRO21",
		0x2a5: "KEY_MACRO22",
		0x2a6: "KEY_MACRO23",
		0x2a7: "KEY_MACRO24",
		0x2a8: "KEY_MACRO25",
		0x2a9: "KEY_MACRO26",
		0x2aa: "KEY_MACRO27",
		0x2ab: "KEY_MACRO28",
		0x2ac: "KEY_MACRO29",
		0x2ad: "KEY_MACRO30",
		0x2b0: "KEY_MACRO_RECORD_START",
		0x2b1: "KEY_MACRO_RECORD_STOP",
		0x2b2: "KEY_MACRO_PRESET_CYCLE",
		0x2b3: "KEY_MACRO_PRESET1",
		0x2b4: "KEY_MACRO_PRESET2",
		0x2b5: "KEY_MACRO_PRESET3",
		0x2b8: "KEY_KBD_LCD_MENU1",
		0x2b9: "KEY_KBD_LCD_MENU2",
		0x2ba: "KEY_KBD_LCD_MENU3",
		0x2bb: "KEY_KBD_LCD_MENU4",
		0x2bc: "KEY_KBD_LCD_MENU5",
		0x2bd: "KEY_PERFORMANCE",
		0x2c0: "BTN_TRIGGER_HAPPY",
		0x2c1: "BTN_TRIGGER_HAPPY2",
		0x2c2: "BTN_TRIGGER_HAPPY3",
		0x2c3: "BTN_TRIGGER_HAPPY4",
		0x2c4: "BTN_TRIGGER_HAPPY5",
		0x2c5: "BTN_TRIGGER_HAPPY6",
		0x2c6: "BTN_TRIGGER_HAPPY7",
		0x2c7: "BTN_TRIGGER_HAPPY8",
		0x2c8: "BTN_TRIGGER_HAPPY9",
		0x2c9: "BTN_TRIGGER_HAPPY10",
		0x2ca: "BTN_TRIGGER_HAPPY11",
		0x2cb: "BTN_TRIGGER_HAPPY12",
		0x2cc: "BTN_TRIGGER_HAPPY13",
		0x2cd: "BTN_TRIGGER_HAPPY14",
		0x2ce: "BTN_TRIGGER_HAPPY15",
		0x2cf: "BTN_TRIGGER_HAPPY16",
		0x2d0: "BTN_TRIGGER_HAPPY17",
		0x2d1: "BTN_TRIGGER_HAPPY18",
		0x2d2: "BTN_TRIGGER_HAPPY19",
		0x2d3: "BTN_TRIGGER_HAPPY20",
		0x2d4: "BTN_TRIGGER_HAPPY21",
		0x2d5: "BTN_TRIGGER_HAPPY22",
		0x2d6: "BTN_TRIGGER_HAPPY23",
		0x2d7: "BTN_TRIGGER_HAPPY24",
		0x2d8: "BTN_TRIGGER_HAPPY25",
		0x2d9: "BTN_TRIGGER_HAPPY26",
		0x2da: "BTN_TRIGGER_HAPPY27",
		0x2db: "BTN_TRIGGER_HAPPY28",
		0x2dc: "BTN_TRIGGER_HAPPY29",
		0x2dd: "BTN_TRIGGER_HAPPY30",
		0x2de: "BTN_TRIGGER_HAPPY31",
		0x2df: "BTN_TRIGGER_HAPPY32",
		0x2e0: "BTN_TRIGGER_HAPPY33",
		0x2e1: "BTN_TRIGGER_HAPPY34",
		0x2e2: "BTN_TRIGGER_HAPPY35",
		0x2e3: "BTN_TRIGGER_HAPPY36",
		0x2e4: "BTN_TRIGGER_HAPPY37",
		0x2e5: "BTN_TRIGGER_HAPPY38",
		0x2e6: "BTN_TRIGGER_HAPPY39",
		0x2e7: "BTN_TRIGGER_HAPPY40",
	},
	EV_LED: {
		0x0: "LED_NUML",
		0x1: "LED_CAPSL",
		0x2: "LED_SCROLLL",
		0x3: "LED_COMPOSE",
		0x4: "LED_KANA",
		0x5: "LED_SLEEP",
		0x6: "LED_SUSPEND",
		0x7: "LED_MUTE",
		0x8: "LED_MISC",
		0x9: "LED_MAIL",
		0xa: "LED_CHARGING",
	},
	EV_MSC: {
		0x0: "MSC_SERIAL",
		0x1: "MSC_PULSELED",
		0x2: "MSC_GESTURE",
		0x3: "MSC_RAW",
		0x4: "MSC_SCAN",
		0x5: "MSC_TIMESTAMP",
	},
	EV_REL: {
		0x0: "REL_X",
		0x1: "REL_Y",
		0x2: "REL_Z",
		0x3: "REL_RX",
		0x4: "REL_RY",
		0x5: "REL_RZ",
		0x6: "REL_HWHEEL",
		0x7: "REL_DIAL",
		0x8: "REL_WHEEL",
		0x9: "REL_MISC",
		0xa: "REL_RESERVED",
		0xb: "REL_WHEEL_HI_RES",
		0xc: "REL_HWHEEL_HI_RES",
	},
	EV_REP: {
		0x0: "REP_DELAY",
		0x1: "REP_PERIOD",
	},
	EV_SND: {
		0x0: "SND_CLICK",
		0x1: "SND_BELL",
		0x2: "SND_TONE",
	},
	EV_SW: {
		0x0:  "SW_LID",
		0x1:  "SW_TABLET_MODE",
		0x2:  "SW_HEADPHONE_INSERT",
		0x3:  "SW_RFKILL_ALL",
		0x4:  "SW_MICROPHONE_INSERT",
		0x5:  "SW_DOCK",
		0x6:  "SW_LINEOUT_INSERT",
		0x7:  "SW_JACK_PHYSICAL_INSERT",
		0x8:  "SW_VIDEOOUT_INSERT",
		0x9:  "SW_CAMERA_LENS_COVER",
		0xa:  "SW_KEYPAD_SLIDE",
		0xb:  "SW_FRONT_PROXIMITY",
		0xc:  "SW_ROTATE_LOCK",
		0xd:  "SW_LINEIN_INSERT",
		0xe:  "SW_MUTE_DEVICE",
		0xf:  "SW_PEN_INSERTED",
		0x10: "SW_MACHINE_COVER",
		0x11: "SW_USB_INSERT",
	},
	EV_SYN: {
		0x0: "SYN_REPORT",
		0x1: "SYN_CONFIG",
		0x2: "SYN_MT_REPORT",
		0x3: "SYN_DROPPED",
	},
}

var evCodeByName = map[string]EvCode{
	"SYN_REPORT":                   0x0,
	"SYN_CONFIG":                   0x1,
	"SYN_MT_REPORT":                0x2,
	"SYN_DROPPED":                  0x3,
	"KEY_RESERVED":                 0x0,
	"KEY_ESC":                      0x1,
	"KEY_1":                        0x2,
	"KEY_2":                        0x3,
	"KEY_3":                        0x4,
	"KEY_4":                        0x5,
	"KEY_5":                        0x6,
	"KEY_6":                        0x7,
	"KEY_7":                        0x8,
	"KEY_8":                        0x9,
	"KEY_9":                        0xa,
	"KEY_0":                        0xb,
	"KEY_MINUS":                    0xc,
	"KEY_EQUAL":                    0xd,
	"KEY_BACKSPACE":                0xe,
	"KEY_TAB":                      0xf,
	"KEY_Q":                        0x10,
	"KEY_W":                        0x11,
	"KEY_E":                        0x12,
	"KEY_R":                        0x13,
	"KEY_T":                        0x14,
	"KEY_Y":                        0x15,
	"KEY_U":                        0x16,
	"KEY_I":                        0x17,
	"KEY_O":                        0x18,
	"KEY_P":                        0x19,
	"KEY_LEFTBRACE":                0x1a,
	"KEY_RIGHTBRACE":               0x1b,
	"KEY_ENTER":                    0x1c,
	"KEY_LEFTCTRL":                 0x1d,
	"KEY_A":                        0x1e,
	"KEY_S":                        0x1f,
	"KEY_D":                        0x20,
	"KEY_F":                        0x21,
	"KEY_G":                        0x22,
	"KEY_H":                        0x23,
	"KEY_J":                        0x24,
	"KEY_K":                        0x25,
	"KEY_L":                        0x26,
	"KEY_SEMICOLON":                0x27,
	"KEY_APOSTROPHE":               0x28,
	"KEY_GRAVE":                    0x29,
	"KEY_LEFTSHIFT":                0x2a,
	"KEY_BACKSLASH":                0x2b,
	"KEY_Z":                        0x2c,
	"KEY_X":                        0x2d,
	"KEY_C":                        0x2e,
	"KEY_V":                        0x2f,
	"KEY_B":                        0x30,
	"KEY_N":                        0x31,
	"KEY_M":                        0x32,
	"KEY_COMMA":                    0x33,
	"KEY_DOT":                      0x34,
	"KEY_SLASH":                    0x35,
	"KEY_RIGHTSHIFT":               0x36,
	"KEY_KPASTERISK":               0x37,
	"KEY_LEFTALT":                  0x38,
	"KEY_SPACE":                    0x39,
	"KEY_CAPSLOCK":                 0x3a,
	"KEY_F1":                       0x3b,
	"KEY_F2":                       0x3c,
	"KEY_F3":                       0x3d,
	"KEY_F4":                       0x3e,
	"KEY_F5":                       0x3f,
	"KEY_F6":                       0x40,
	"KEY_F7":                       0x41,
	"KEY_F8":                       0x42,
	"KEY_F9":                       0x43,
	"KEY_F10":                      0x44,
	"KEY_NUMLOCK":                  0x45,
	"KEY_SCROLLLOCK":               0x46,
	"KEY_KP7":                      0x47,
	"KEY_KP8":                      0x48,
	"KEY_KP9":                      0x49,
	"KEY_KPMINUS":                  0x4a,
	"KEY_KP4":                      0x4b,
	"KEY_KP5":                      0x4c,
	"KEY_KP6":                      0x4d,
	"KEY_KPPLUS":                   0x4e,
	"KEY_KP1":                      0x4f,
	"KEY_KP2":                      0x50,
	"KEY_KP3":                      0x51,
	"KEY_KP0":                      0x52,
	"KEY_KPDOT":                    0x53,
	"KEY_ZENKAKUHANKAKU":           0x55,
	"KEY_102ND":                    0x56,
	"KEY_F11":                      0x57,
	"KEY_F12":                      0x58,
	"KEY_RO":                       0x59,
	"KEY_KATAKANA":                 0x5a,
	"KEY_HIRAGANA":                 0x5b,
	"KEY_HENKAN":                   0x5c,
	"KEY_KATAKANAHIRAGANA":         0x5d,
	"KEY_MUHENKAN":                 0x5e,
	"KEY_KPJPCOMMA":                0x5f,
	"KEY_KPENTER":                  0x60,
	"KEY_RIGHTCTRL":                0x61,
	"KEY_KPSLASH":                  0x62,
	"KEY_SYSRQ":                    0x63,
	"KEY_RIGHTALT":                 0x64,
	"KEY_LINEFEED":                 0x65,
	"KEY_HOME":                     0x66,
	"KEY_UP":                       0x67,
	"KEY_PAGEUP":                   0x68,
	"KEY_LEFT":                     0x69,
	"KEY_RIGHT":                    0x6a,
	"KEY_END":                      0x6b,
	"KEY_DOWN":                     0x6c,
	"KEY_PAGEDOWN":                 0x6d,
	"KEY_INSERT":                   0x6e,
	"KEY_DELETE":                   0x6f,
	"KEY_MACRO":                    0x70,
	"KEY_MUTE":                     0x71,
	"KEY_VOLUMEDOWN":               0x72,
	"KEY_VOLUMEUP":                 0x73,
	"KEY_POWER":                    0x74,
	"KEY_KPEQUAL":                  0x75,
	"KEY_KPPLUSMINUS":              0x76,
	"KEY_PAUSE":                    0x77,
	"KEY_SCALE":                    0x78,
	"KEY_KPCOMMA":                  0x79,
	"KEY_HANGEUL":                  0x7a,
	"KEY_HANGUEL":                  0x7a,
	"KEY_HANJA":                    0x7b,
	"KEY_YEN":                      0x7c,
	"KEY_LEFTMETA":                 0x7d,
	"KEY_RIGHTMETA":                0x7e,
	"KEY_COMPOSE":                  0x7f,
	"KEY_STOP":                     0x80,
	"KEY_AGAIN":                    0x81,
	"KEY_PROPS":                    0x82,
	"KEY_UNDO":                     0x83,
	"KEY_FRONT":                    0x84,
	"KEY_COPY":                     0x85,
	"KEY_OPEN":                     0x86,
	"KEY_PASTE":                    0x87,
	"KEY_FIND":                     0x88,
	"KEY_CUT":                      0x89,
	"KEY_HELP":                     0x8a,
	"KEY_MENU":                     0x8b,
	"KEY_CALC":                     0x8c,
	"KEY_SETUP":                    0x8d,
	"KEY_SLEEP":                    0x8e,
	"KEY_WAKEUP":                   0x8f,
	"KEY_FILE":                     0x90,
	"KEY_SENDFILE":                 0x91,
	"KEY_DELETEFILE":               0x92,
	"KEY_XFER":                     0x93,
	"KEY_PROG1":                    0x94,
	"KEY_PROG2":                    0x95,
	"KEY_WWW":                      0x96,
	"KEY_MSDOS":                    0x97,
	"KEY_COFFEE":                   0x98,
	"KEY_SCREENLOCK":               0x98,
	"KEY_ROTATE_DISPLAY":           0x99,
	"KEY_DIRECTION":                0x99,
	"KEY_CYCLEWINDOWS":             0x9a,
	"KEY_MAIL":                     0x9b,
	"KEY_BOOKMARKS":                0x9c,
	"KEY_COMPUTER":                 0x9d,
	"KEY_BACK":                     0x9e,
	"KEY_FORWARD":                  0x9f,
	"KEY_CLOSECD":                  0xa0,
	"KEY_EJECTCD":                  0xa1,
	"KEY_EJECTCLOSECD":             0xa2,
	"KEY_NEXTSONG":                 0xa3,
	"KEY_PLAYPAUSE":                0xa4,
	"KEY_PREVIOUSSONG":             0xa5,
	"KEY_STOPCD":                   0xa6,
	"KEY_RECORD":                   0xa7,
	"KEY_REWIND":                   0xa8,
	"KEY_PHONE":                    0xa9,
	"KEY_ISO":                      0xaa,
	"KEY_CONFIG":                   0xab,
	"KEY_HOMEPAGE":                 0xac,
	"KEY_REFRESH":                  0xad,
	"KEY_EXIT":                     0xae,
	"KEY_MOVE":                     0xaf,
	"KEY_EDIT":                     0xb0,
	"KEY_SCROLLUP":                 0xb1,
	"KEY_SCROLLDOWN":               0xb2,
	"KEY_KPLEFTPAREN":              0xb3,
	"KEY_KPRIGHTPAREN":             0xb4,
	"KEY_NEW":                      0xb5,
	"KEY_REDO":                     0xb6,
	"KEY_F13":                      0xb7,
	"KEY_F14":                      0xb8,
	"KEY_F15":                      0xb9,
	"KEY_F16":                      0xba,
	"KEY_F17":                      0xbb,
	"KEY_F18":                      0xbc,
	"KEY_F19":                      0xbd,
	"KEY_F20":                      0xbe,
	"KEY_F21":                      0xbf,
	"KEY_F22":                      0xc0,
	"KEY_F23":                      0xc1,
	"KEY_F24":                      0xc2,
	"KEY_PLAYCD":                   0xc8,
	"KEY_PAUSECD":                  0xc9,
	"KEY_PROG3":                    0xca,
	"KEY_PROG4":                    0xcb,
	"KEY_ALL_APPLICATIONS":         0xcc,
	"KEY_DASHBOARD":                0xcc,
	"KEY_SUSPEND":                  0xcd,
	"KEY_CLOSE":                    0xce,
	"KEY_PLAY":                     0xcf,
	"KEY_FASTFORWARD":              0xd0,
	"KEY_BASSBOOST":                0xd1,
	"KEY_PRINT":                    0xd2,
	"KEY_HP":                       0xd3,
	"KEY_CAMERA":                   0xd4,
	"KEY_SOUND":                    0xd5,
	"KEY_QUESTION":                 0xd6,
	"KEY_EMAIL":                    0xd7,
	"KEY_CHAT":                     0xd8,
	"KEY_SEARCH":                   0xd9,
	"KEY_CONNECT":                  0xda,
	"KEY_FINANCE":                  0xdb,
	"KEY_SPORT":                    0xdc,
	"KEY_SHOP":                     0xdd,
	"KEY_ALTERASE":                 0xde,
	"KEY_CANCEL":                   0xdf,
	"KEY_BRIGHTNESSDOWN":           0xe0,
	"KEY_BRIGHTNESSUP":             0xe1,
	"KEY_MEDIA":                    0xe2,
	"KEY_SWITCHVIDEOMODE":          0xe3,
	"KEY_KBDILLUMTOGGLE":           0xe4,
	"KEY_KBDILLUMDOWN":             0xe5,
	"KEY_KBDILLUMUP":               0xe6,
	"KEY_SEND":                     0xe7,
	"KEY_REPLY":                    0xe8,
	"KEY_FORWARDMAIL":              0xe9,
	"KEY_SAVE":                     0xea,
	"KEY_DOCUMENTS":                0xeb,
	"KEY_BATTERY":                  0xec,
	"KEY_BLUETOOTH":                0xed,
	"KEY_WLAN":                     0xee,
	"KEY_UWB":                      0xef,
	"KEY_UNKNOWN":                  0xf0,
	"KEY_VIDEO_NEXT":               0xf1,
	"KEY_VIDEO_PREV":               0xf2,
	"KEY_BRIGHTNESS_CYCLE":         0xf3,
	"KEY_BRIGHTNESS_AUTO":          0xf4,
	"KEY_BRIGHTNESS_ZERO":          0xf4,
	"KEY_DISPLAY_OFF":              0xf5,
	"KEY_WWAN":                     0xf6,
	"KEY_WIMAX":                    0xf6,
	"KEY_RFKILL":                   0xf7,
	"KEY_MICMUTE":                  0xf8,
	"BTN_MISC":                     0x100,
	"BTN_0":                        0x100,
	"BTN_1":                        0x101,
	"BTN_2":                        0x102,
	"BTN_3":                        0x103,
	"BTN_4":                        0x104,
	"BTN_5":                        0x105,
	"BTN_6":                        0x106,
	"BTN_7":                        0x107,
	"BTN_8":                        0x108,
	"BTN_9":                        0x109,
	"BTN_MOUSE":                    0x110,
	"BTN_LEFT":                     0x110,
	"BTN_RIGHT":                    0x111,
	"BTN_MIDDLE":                   0x112,
	"BTN_SIDE":                     0x113,
	"BTN_EXTRA":                    0x114,
	"BTN_FORWARD":                  0x115,
	"BTN_BACK":                     0x116,
	"BTN_TASK":                     0x117,
	"BTN_JOYSTICK":                 0x120,
	"BTN_TRIGGER":                  0x120,
	"BTN_THUMB":                    0x121,
	"BTN_THUMB2":                   0x122,
	"BTN_TOP":                      0x123,
	"BTN_TOP2":                     0x124,
	"BTN_PINKIE":                   0x125,
	"BTN_BASE":                     0x126,
	"BTN_BASE2":                    0x127,
	"BTN_BASE3":                    0x128,
	"BTN_BASE4":                    0x129,
	"BTN_BASE5":                    0x12a,
	"BTN_BASE6":                    0x12b,
	"BTN_DEAD":                     0x12f,
	"BTN_GAMEPAD":                  0x130,
	"BTN_SOUTH":                    0x130,
	"BTN_A":                        0x130,
	"BTN_EAST":                     0x131,
	"BTN_B":                        0x131,
	"BTN_C":                        0x132,
	"BTN_NORTH":                    0x133,
	"BTN_X":                        0x133,
	"BTN_WEST":                     0x134,
	"BTN_Y":                        0x134,
	"BTN_Z":                        0x135,
	"BTN_TL":                       0x136,
	"BTN_TR":                       0x137,
	"BTN_TL2":                      0x138,
	"BTN_TR2":                      0x139,
	"BTN_SELECT":                   0x13a,
	"BTN_START":                    0x13b,
	"BTN_MODE":                     0x13c,
	"BTN_THUMBL":                   0x13d,
	"BTN_THUMBR":                   0x13e,
	"BTN_DIGI":                     0x140,
	"BTN_TOOL_PEN":                 0x140,
	"BTN_TOOL_RUBBER":              0x141,
	"BTN_TOOL_BRUSH":               0x142,
	"BTN_TOOL_PENCIL":              0x143,
	"BTN_TOOL_AIRBRUSH":            0x144,
	"BTN_TOOL_FINGER":              0x145,
	"BTN_TOOL_MOUSE":               0x146,
	"BTN_TOOL_LENS":                0x147,
	"BTN_TOOL_QUINTTAP":            0x148,
	"BTN_STYLUS3":                  0x149,
	"BTN_TOUCH":                    0x14a,
	"BTN_STYLUS":                   0x14b,
	"BTN_STYLUS2":                  0x14c,
	"BTN_TOOL_DOUBLETAP":           0x14d,
	"BTN_TOOL_TRIPLETAP":           0x14e,
	"BTN_TOOL_QUADTAP":             0x14f,
	"BTN_WHEEL":                    0x150,
	"BTN_GEAR_DOWN":                0x150,
	"BTN_GEAR_UP":                  0x151,
	"KEY_OK":                       0x160,
	"KEY_SELECT":                   0x161,
	"KEY_GOTO":                     0x162,
	"KEY_CLEAR":                    0x163,
	"KEY_POWER2":                   0x164,
	"KEY_OPTION":                   0x165,
	"KEY_INFO":                     0x166,
	"KEY_TIME":                     0x167,
	"KEY_VENDOR":                   0x168,
	"KEY_ARCHIVE":                  0x169,
	"KEY_PROGRAM":                  0x16a,
	"KEY_CHANNEL":                  0x16b,
	"KEY_FAVORITES":                0x16c,
	"KEY_EPG":                      0x16d,
	"KEY_PVR":                      0x16e,
	"KEY_MHP":                      0x16f,
	"KEY_LANGUAGE":                 0x170,
	"KEY_TITLE":                    0x171,
	"KEY_SUBTITLE":                 0x172,
	"KEY_ANGLE":                    0x173,
	"KEY_FULL_SCREEN":              0x174,
	"KEY_ZOOM":                     0x174,
	"KEY_MODE":                     0x175,
	"KEY_KEYBOARD":                 0x176,
	"KEY_ASPECT_RATIO":             0x177,
	"KEY_SCREEN":                   0x177,
	"KEY_PC":                       0x178,
	"KEY_TV":                       0x179,
	"KEY_TV2":                      0x17a,
	"KEY_VCR":                      0x17b,
	"KEY_VCR2":                     0x17c,
	"KEY_SAT":                      0x17d,
	"KEY_SAT2":                     0x17e,
	"KEY_CD":                       0x17f,
	"KEY_TAPE":                     0x180,
	"KEY_RADIO":                    0x181,
	"KEY_TUNER":                    0x182,
	"KEY_PLAYER":                   0x183,
	"KEY_TEXT":                     0x184,
	"KEY_DVD":                      0x185,
	"KEY_AUX":                      0x186,
	"KEY_MP3":                      0x187,
	"KEY_AUDIO":                    0x188,
	"KEY_VIDEO":                    0x189,
	"KEY_DIRECTORY":                0x18a,
	"KEY_LIST":                     0x18b,
	"KEY_MEMO":                     0x18c,
	"KEY_CALENDAR":                 0x18d,
	"KEY_RED":                      0x18e,
	"KEY_GREEN":                    0x18f,
	"KEY_YELLOW":                   0x190,
	"KEY_BLUE":                     0x191,
	"KEY_CHANNELUP":                0x192,
	"KEY_CHANNELDOWN":              0x193,
	"KEY_FIRST":                    0x194,
	"KEY_LAST":                     0x195,
	"KEY_AB":                       0x196,
	"KEY_NEXT":                     0x197,
	"KEY_RESTART":                  0x198,
	"KEY_SLOW":                     0x199,
	"KEY_SHUFFLE":                  0x19a,
	"KEY_BREAK":                    0x19b,
	"KEY_PREVIOUS":                 0x19c,
	"KEY_DIGITS":                   0x19d,
	"KEY_TEEN":                     0x19e,
	"KEY_TWEN":                     0x19f,
	"KEY_VIDEOPHONE":               0x1a0,
	"KEY_GAMES":                    0x1a1,
	"KEY_ZOOMIN":                   0x1a2,
	"KEY_ZOOMOUT":                  0x1a3,
	"KEY_ZOOMRESET":                0x1a4,
	"KEY_WORDPROCESSOR":            0x1a5,
	"KEY_EDITOR":                   0x1a6,
	"KEY_SPREADSHEET":              0x1a7,
	"KEY_GRAPHICSEDITOR":           0x1a8,
	"KEY_PRESENTATION":             0x1a9,
	"KEY_DATABASE":                 0x1aa,
	"KEY_NEWS":                     0x1ab,
	"KEY_VOICEMAIL":                0x1ac,
	"KEY_ADDRESSBOOK":              0x1ad,
	"KEY_MESSENGER":                0x1ae,
	"KEY_DISPLAYTOGGLE":            0x1af,
	"KEY_BRIGHTNESS_TOGGLE":        0x1af,
	"KEY_SPELLCHECK":               0x1b0,
	"KEY_LOGOFF":                   0x1b1,
	"KEY_DOLLAR":                   0x1b2,
	"KEY_EURO":                     0x1b3,
	"KEY_FRAMEBACK":                0x1b4,
	"KEY_FRAMEFORWARD":             0x1b5,
	"KEY_CONTEXT_MENU":             0x1b6,
	"KEY_MEDIA_REPEAT":             0x1b7,
	"KEY_10CHANNELSUP":             0x1b8,
	"KEY_10CHANNELSDOWN":           0x1b9,
	"KEY_IMAGES":                   0x1ba,
	"KEY_NOTIFICATION_CENTER":      0x1bc,
	"KEY_PICKUP_PHONE":             0x1bd,
	"KEY_HANGUP_PHONE":             0x1be,
	"KEY_LINK_PHONE":               0x1bf,
	"KEY_DEL_EOL":                  0x1c0,
	"KEY_DEL_EOS":                  0x1c1,
	"KEY_INS_LINE":                 0x1c2,
	"KEY_DEL_LINE":                 0x1c3,
	"KEY_FN":                       0x1d0,
	"KEY_FN_ESC":                   0x1d1,
	"KEY_FN_F1":                    0x1d2,
	"KEY_FN_F2":                    0x1d3,
	"KEY_FN_F3":                    0x1d4,
	"KEY_FN_F4":                    0x1d5,
	"KEY_FN_F5":                    0x1d6,
	"KEY_FN_F6":                    0x1d7,
	"KEY_FN_F7":                    0x1d8,
	"KEY_FN_F8":                    0x1d9,
	"KEY_FN_F9":                    0x1da,
	"KEY_FN_F10":                   0x1db,
	"KEY_FN_F11":                   0x1dc,
	"KEY_FN_F12":                   0x1dd,
	"KEY_FN_1":                     0x1de,
	"KEY_FN_2":                     0x1df,
	"KEY_FN_D":                     0x1e0,
	"KEY_FN_E":                     0x1e1,
	"KEY_FN_F":                     0x1e2,
	"KEY_FN_S":                     0x1e3,
	"KEY_FN_B":                     0x1e4,
	"KEY_FN_RIGHT_SHIFT":           0x1e5,
	"KEY_BRL_DOT1":                 0x1f1,
	"KEY_BRL_DOT2":                 0x1f2,
	"KEY_BRL_DOT3":                 0x1f3,
	"KEY_BRL_DOT4":                 0x1f4,
	"KEY_BRL_DOT5":                 0x1f5,
	"KEY_BRL_DOT6":                 0x1f6,
	"KEY_BRL_DOT7":                 0x1f7,
	"KEY_BRL_DOT8":                 0x1f8,
	"KEY_BRL_DOT9":                 0x1f9,
	"KEY_BRL_DOT10":                0x1fa,
	"KEY_NUMERIC_0":                0x200,
	"KEY_NUMERIC_1":                0x201,
	"KEY_NUMERIC_2":                0x202,
	"KEY_NUMERIC_3":                0x203,
	"KEY_NUMERIC_4":                0x204,
	"KEY_NUMERIC_5":                0x205,
	"KEY_NUMERIC_6":                0x206,
	"KEY_NUMERIC_7":                0x207,
	"KEY_NUMERIC_8":                0x208,
	"KEY_NUMERIC_9":                0x209,
	"KEY_NUMERIC_STAR":             0x20a,
	"KEY_NUMERIC_POUND":            0x20b,
	"KEY_NUMERIC_A":                0x20c,
	"KEY_NUMERIC_B":                0x20d,
	"KEY_NUMERIC_C":                0x20e,
	"KEY_NUMERIC_D":                0x20f,
	"KEY_CAMERA_FOCUS":             0x210,
	"KEY_WPS_BUTTON":               0x211,
	"KEY_TOUCHPAD_TOGGLE":          0x212,
	"KEY_TOUCHPAD_ON":              0x213,
	"KEY_TOUCHPAD_OFF":             0x214,
	"KEY_CAMERA_ZOOMIN":            0x215,
	"KEY_CAMERA_ZOOMOUT":           0x216,
	"KEY_CAMERA_UP":                0x217,
	"KEY_CAMERA_DOWN":              0x218,
	"KEY_CAMERA_LEFT":              0x219,
	"KEY_CAMERA_RIGHT":             0x21a,
	"KEY_ATTENDANT_ON":             0x21b,
	"KEY_ATTENDANT_OFF":            0x21c,
	"KEY_ATTENDANT_TOGGLE":         0x21d,
	"KEY_LIGHTS_TOGGLE":            0x21e,
	"BTN_DPAD_UP":                  0x220,
	"BTN_DPAD_DOWN":                0x221,
	"BTN_DPAD_LEFT":                0x222,
	"BTN_DPAD_RIGHT":               0x223,
	"BTN_GRIPL":                    0x224,
	"BTN_GRIPR":                    0x225,
	"BTN_GRIPL2":                   0x226,
	"BTN_GRIPR2":                   0x227,
	"KEY_ALS_TOGGLE":               0x230,
	"KEY_ROTATE_LOCK_TOGGLE":       0x231,
	"KEY_REFRESH_RATE_TOGGLE":      0x232,
	"KEY_BUTTONCONFIG":             0x240,
	"KEY_TASKMANAGER":              0x241,
	"KEY_JOURNAL":                  0x242,
	"KEY_CONTROLPANEL":             0x243,
	"KEY_APPSELECT":                0x244,
	"KEY_SCREENSAVER":              0x245,
	"KEY_VOICECOMMAND":             0x246,
	"KEY_ASSISTANT":                0x247,
	"KEY_KBD_LAYOUT_NEXT":          0x248,
	"KEY_EMOJI_PICKER":             0x249,
	"KEY_DICTATE":                  0x24a,
	"KEY_CAMERA_ACCESS_ENABLE":     0x24b,
	"KEY_CAMERA_ACCESS_DISABLE":    0x24c,
	"KEY_CAMERA_ACCESS_TOGGLE":     0x24d,
	"KEY_ACCESSIBILITY":            0x24e,
	"KEY_DO_NOT_DISTURB":           0x24f,
	"KEY_BRIGHTNESS_MIN":           0x250,
	"KEY_EPRIVACY_SCREEN_ON":       0x252,
	"KEY_EPRIVACY_SCREEN_OFF":      0x253,
	"KEY_ACTION_ON_SELECTION":      0x254,
	"KEY_CONTEXTUAL_INSERT":        0x255,
	"KEY_CONTEXTUAL_QUERY":         0x256,
	"KEY_KBDINPUTASSIST_PREV":      0x260,
	"KEY_KBDINPUTASSIST_NEXT":      0x261,
	"KEY_KBDINPUTASSIST_PREVGROUP": 0x262,
	"KEY_KBDINPUTASSIST_NEXTGROUP": 0x263,
	"KEY_KBDINPUTASSIST_ACCEPT":    0x264,
	"KEY_KBDINPUTASSIST_CANCEL":    0x265,
	"KEY_RIGHT_UP":                 0x266,
	"KEY_RIGHT_DOWN":               0x267,
	"KEY_LEFT_UP":                  0x268,
	"KEY_LEFT_DOWN":                0x269,
	"KEY_ROOT_MENU":                0x26a,
	"KEY_MEDIA_TOP_MENU":           0x26b,
	"KEY_NUMERIC_11":               0x26c,
	"KEY_NUMERIC_12":               0x26d,
	"KEY_AUDIO_DESC":               0x26e,
	"KEY_3D_MODE":                  0x26f,
	"KEY_NEXT_FAVORITE":            0x270,
	"KEY_STOP_RECORD":              0x271,
	"KEY_PAUSE_RECORD":             0x272,
	"KEY_VOD":                      0x273,
	"KEY_UNMUTE":                   0x274,
	"KEY_FASTREVERSE":              0x275,
	"KEY_SLOWREVERSE":              0x276,
	"KEY_DATA":                     0x277,
	"KEY_ONSCREEN_KEYBOARD":        0x278,
	"KEY_PRIVACY_SCREEN_TOGGLE":    0x279,
	"KEY_SELECTIVE_SCREENSHOT":     0x27a,
	"KEY_NEXT_ELEMENT":             0x27b,
	"KEY_PREVIOUS_ELEMENT":         0x27c,
	"KEY_AUTOPILOT_ENGAGE_TOGGLE":  0x27d,
	"KEY_MARK_WAYPOINT":            0x27e,
	"KEY_SOS":                      0x27f,
	"KEY_NAV_CHART":                0x280,
	"KEY_FISHING_CHART":            0x281,
	"KEY_SINGLE_RANGE_RADAR":       0x282,
	"KEY_DUAL_RANGE_RADAR":         0x283,
	"KEY_RADAR_OVERLAY":            0x284,
	"KEY_TRADITIONAL_SONAR":        0x285,
	"KEY_CLEARVU_SONAR":            0x286,
	"KEY_SIDEVU_SONAR":             0x287,
	"KEY_NAV_INFO":                 0x288,
	"KEY_BRIGHTNESS_MENU":          0x289,
	"KEY_MACRO1":                   0x290,
	"KEY_MACRO2":                   0x291,
	"KEY_MACRO3":                   0x292,
	"KEY_MACRO4":                   0x293,
	"KEY_MACRO5":                   0x294,
	"KEY_MACRO6":                   0x295,
	"KEY_MACRO7":                   0x296,
	"KEY_MACRO8":                   0x297,
	"KEY_MACRO9":                   0x298,
	"KEY_MACRO10":                  0x299,
	"KEY_MACRO11":                  0x29a,
	"KEY_MACRO12":                  0x29b,
	"KEY_MACRO13":                  0x29c,
	"KEY_MACRO14":                  0x29d,
	"KEY_MACRO15":                  0x29e,
	"KEY_MACRO16":                  0x29f,
	"KEY_MACRO17":                  0x2a0,
	"KEY_MACRO18":                  0x2a1,
	"KEY_MACRO19":                  0x2a2,
	"KEY_MACRO20":                  0x2a3,
	"KEY_MACRO21":                  0x2a4,
	"KEY_MACRO22":                  0x2a5,
	"KEY_MACRO23":                  0x2a6,
	"KEY_MACRO24":                  0x2a7,
	"KEY_MACRO25":                  0x2a8,
	"KEY_MACRO26":                  0x2a9,
	"KEY_MACRO27":                  0x2aa,
	"KEY_MACRO28":                  0x2ab,
	"KEY_MACRO29":                  0x2ac,
	"KEY_MACRO30":                  0x2ad,
	"KEY_MACRO_RECORD_START":       0x2b0,
	"KEY_MACRO_RECORD_STOP":        0x2b1,
	"KEY_MACRO_PRESET_CYCLE":       0x2b2,
	"KEY_MACRO_PRESET1":            0x2b3,
	"KEY_MACRO_PRESET2":            0x2b4,
	"KEY_MACRO_PRESET3":            0x2b5,
	"KEY_KBD_LCD_MENU1":            0x2b8,
	"KEY_KBD_LCD_MENU2":            0x2b9,
	"KEY_KBD_LCD_MENU3":            0x2ba,
	"KEY_KBD_LCD_MENU4":            0x2bb,
	"KEY_KBD_LCD_MENU5":            0x2bc,
	"KEY_PERFORMANCE":              0x2bd,
	"BTN_TRIGGER_HAPPY":            0x2c0,
	"BTN_TRIGGER_HAPPY1":           0x2c0,
	"BTN_TRIGGER_HAPPY2":           0x2c1,
	"BTN_TRIGGER_HAPPY3":           0x2c2,
	"BTN_TRIGGER_HAPPY4":           0x2c3,
	"BTN_TRIGGER_HAPPY5":           0x2c4,
	"BTN_TRIGGER_HAPPY6":           0x2c5,
	"BTN_TRIGGER_HAPPY7":           0x2c6,
	"BTN_TRIGGER_HAPPY8":           0x2c7,
	"BTN_TRIGGER_HAPPY9":           0x2c8,
	"BTN_TRIGGER_HAPPY10":          0x2c9,
	"BTN_TRIGGER_HAPPY11":          0x2ca,
	"BTN_TRIGGER_HAPPY12":          0x2cb,
	"BTN_TRIGGER_HAPPY13":          0x2cc,
	"BTN_TRIGGER_HAPPY14":          0x2cd,
	"BTN_TRIGGER_HAPPY15":          0x2ce,
	"BTN_TRIGGER_HAPPY16":          0x2cf,
	"BTN_TRIGGER_HAPPY17":          0x2d0,
	"BTN_TRIGGER_HAPPY18":          0x2d1,
	"BTN_TRIGGER_HAPPY19":          0x2d2,
	"BTN_TRIGGER_HAPPY20":          0x2d3,
	"BTN_TRIGGER_HAPPY21":          0x2d4,
	"BTN_TRIGGER_HAPPY22":          0x2d5,
	"BTN_TRIGGER_HAPPY23":          0x2d6,
	"BTN_TRIGGER_HAPPY24":          0x2d7,
	"BTN_TRIGGER_HAPPY25":          0x2d8,
	"BTN_TRIGGER_HAPPY26":          0x2d9,
	"BTN_TRIGGER_HAPPY27":          0x2da,
	"BTN_TRIGGER_HAPPY28":          0x2db,
	"BTN_TRIGGER_HAPPY29":          0x2dc,
	"BTN_TRIGGER_HAPPY30":          0x2dd,
	"BTN_TRIGGER_HAPPY31":          0x2de,
	"BTN_TRIGGER_HAPPY32":          0x2df,
	"BTN_TRIGGER_HAPPY33":          0x2e0,
	"BTN_TRIGGER_HAPPY34":          0x2e1,
	"BTN_TRIGGER_HAPPY35":          0x2e2,
	"BTN_TRIGGER_HAPPY36":          0x2e3,
	"BTN_TRIGGER_HAPPY37":          0x2e4,
	"BTN_TRIGGER_HAPPY38":          0x2e5,
	"BTN_TRIGGER_HAPPY39":          0x2e6,
	"BTN_TRIGGER_HAPPY40":          0x2e7,
	"KEY_MIN_INTERESTING":          0x71,
	"REL_X":                        0x0,
	"REL_Y":                        0x1,
	"REL_Z":                        0x2,
	"REL_RX":                       0x3,
	"REL_RY":                       0x4,
	"REL_RZ":                       0x5,
	"REL_HWHEEL":                   0x6,
	"REL_DIAL":                     0x7,
	"REL_WHEEL":                    0x8,
	"REL_MISC":                     0x9,
	"REL_RESERVED":                 0xa,
	"REL_WHEEL_HI_RES":             0xb,
	"REL_HWHEEL_HI_RES":            0xc,
	"ABS_X":                        0x0,
	"ABS_Y":                        0x1,
	"ABS_Z":                        0x2,
	"ABS_RX":                       0x3,
	"ABS_RY":                       0x4,
	"ABS_RZ":                       0x5,
	"ABS_THROTTLE":                 0x6,
	"ABS_RUDDER":                   0x7,
	"ABS_WHEEL":                    0x8,
	"ABS_GAS":                      0x9,
	"ABS_BRAKE":                    0xa,
	"ABS_HAT0X":                    0x10,
	"ABS_HAT0Y":                    0x11,
	"ABS_HAT1X":                    0x12,
	"ABS_HAT1Y":                    0x13,
	"ABS_HAT2X":                    0x14,
	"ABS_HAT2Y":                    0x15,
	"ABS_HAT3X":                    0x16,
	"ABS_HAT3Y":                    0x17,
	"ABS_PRESSURE":                 0x18,
	"ABS_DISTANCE":                 0x19,
	"ABS_TILT_X":                   0x1a,
	"ABS_TILT_Y":                   0x1b,
	"ABS_TOOL_WIDTH":               0x1c,
	"ABS_VOLUME":                   0x20,
	"ABS_PROFILE":                  0x21,
	"ABS_SND_PROFILE":              0x22,
	"ABS_MISC":                     0x28,
	"ABS_RESERVED":                 0x2e,
	"ABS_MT_SLOT":                  0x2f,
	"ABS_MT_TOUCH_MAJOR":           0x30,
	"ABS_MT_TOUCH_MINOR":           0x31,
	"ABS_MT_WIDTH_MAJOR":           0x32,
	"ABS_MT_WIDTH_MINOR":           0x33,
	"ABS_MT_ORIENTATION":           0x34,
	"ABS_MT_POSITION_X":            0x35,
	"ABS_MT_POSITION_Y":            0x36,
	"ABS_MT_TOOL_TYPE":             0x37,
	"ABS_MT_BLOB_ID":               0x38,
	"ABS_MT_TRACKING_ID":           0x39,
	"ABS_MT_PRESSURE":              0x3a,
	"ABS_MT_DISTANCE":              0x3b,
	"ABS_MT_TOOL_X":                0x3c,
	"ABS_MT_TOOL_Y":                0x3d,
	"SW_LID":                       0x0,
	"SW_TABLET_MODE":               0x1,
	"SW_HEADPHONE_INSERT":          0x2,
	"SW_RFKILL_ALL":                0x3,
	"SW_RADIO":                     0x3,
	"SW_MICROPHONE_INSERT":         0x4,
	"SW_DOCK":                      0x5,
	"SW_LINEOUT_INSERT":            0x6,
	"SW_JACK_PHYSICAL_INSERT":      0x7,
	"SW_VIDEOOUT_INSERT":           0x8,
	"SW_CAMERA_LENS_COVER":         0x9,
	"SW_KEYPAD_SLIDE":              0xa,
	"SW_FRONT_PROXIMITY":           0xb,
	"SW_ROTATE_LOCK":               0xc,
	"SW_LINEIN_INSERT":             0xd,
	"SW_MUTE_DEVICE":               0xe,
	"SW_PEN_INSERTED":              0xf,
	"SW_MACHINE_COVER":             0x10,
	"SW_USB_INSERT":                0x11,
	"MSC_SERIAL":                   0x0,
	"MSC_PULSELED":                 0x1,
	"MSC_GESTURE":                  0x2,
	"MSC_RAW":                      0x3,
	"MSC_SCAN":                     0x4,
	"MSC_TIMESTAMP":                0x5,
	"LED_NUML":                     0x0,
	"LED_CAPSL":                    0x1,
	"LED_SCROLLL":                  0x2,
	"LED_COMPOSE":                  0x3,
	"LED_KANA":                     0x4,
	"LED_SLEEP":                    0x5,
	"LED_SUSPEND":                  0x6,
	"LED_MUTE":                     0x7,
	"LED_MISC":                     0x8,
	"LED_MAIL":                     0x9,
	"LED_CHARGING":                 0xa,
	"REP_DELAY":                    0x0,
	"REP_PERIOD":                   0x1,
	"SND_CLICK":                    0x0,
	"SND_BELL":                     0x1,
	"SND_TONE":                     0x2,
	"SND_PROFILE_SILENT":           0x0,
	"SND_PROFILE_VIBRATE":          0x1,
	"SND_PROFILE_RING":             0x2,
}

var busNames = map[BusType]string{
	BUS_PCI:         "BUS_PCI",
	BUS_ISAPNP:      "BUS_ISAPNP",
	BUS_USB:         "BUS_USB",
	BUS_HIL:         "BUS_HIL",
	BUS_BLUETOOTH:   "BUS_BLUETOOTH",
	BUS_VIRTUAL:     "BUS_VIRTUAL",
	BUS_ISA:         "BUS_ISA",
	BUS_I8042:       "BUS_I8042",
	BUS_XTKBD:       "BUS_XTKBD",
	BUS_RS232:       "BUS_RS232",
	BUS_GAMEPORT:    "BUS_GAMEPORT",
	BUS_PARPORT:     "BUS_PARPORT",
	BUS_AMIGA:       "BUS_AMIGA",
	BUS_ADB:         "BUS_ADB",
	BUS_I2C:         "BUS_I2C",
	BUS_HOST:        "BUS_HOST",
	BUS_GSC:         "BUS_GSC",
	BUS_ATARI:       "BUS_ATARI",
	BUS_SPI:         "BUS_SPI",
	BUS_RMI:         "BUS_RMI",
	BUS_CEC:         "BUS_CEC",
	BUS_INTEL_ISHTP: "BUS_INTEL_ISHTP",
	BUS_AMD_SFH:     "BUS_AMD_SFH",
	BUS_SDW:         "BUS_SDW",
}
